// BP01 — one entry per printed card number.
//
// Each card carries what is printed on it AND what it does. See
// src/cardDef.ts for the shape, and _EXAMPLE.ts for a filled-in card.
//
// Generated by `npm run sync:cards`; new card numbers are appended and
// anything already here is left untouched. Fill these in by hand.
import { defineCard } from "../cardDef";
import type { CardDef } from "../cardDef";

export const BP01: CardDef[] = [
  defineCard({
    type: "leader",
    id: "BP01-001",
    name: "Camellya",
    character: "Camellya",
    set: "BP01",
    imageId: "BP01-001",
    altImageIds: ["BP01-001_4", "BP01-001_5"],
    level: 2,
    rarity: 3,
    weapon: "sword",
    element: "havoc",
    effects: [
      {
        condition: ["levelUp"],
        text: {
          th: "[Level up] นำการ์ดใบนี้กลับเข้า Character deck",
          en: "[Level up] Return this card to the Character deck",
        },
        resolve: (ctx) => ctx.returnToCharacterDeck(),
      },
      {
        condition: ["leader"],
        text: {
          th: "[Leader] ดาเมจที่เจ้าของได้รับ +1 การ์ดสีแดงของ「Camellya」ได้รับ +1 ดาเมจ",
          en: "[Leader] Damage its owner takes +1. 「Camellya」 red cards gain +1 damage.",
        },
        resolve: (ctx) => {
          // One printed Leader line has two continuous clauses: every hit
          // against this player gets +1, while their red Camellya action
          // cards get +1 attack (the runtime value used as card damage).
          ctx.modifyDamageTaken(+1);
          ctx.buff({ character: "Camellya", color: "red" }, "attack", +1);
        },
      },
    ],
  }),
  defineCard({
    type: "leader",
    id: "BP01-002",
    name: "Camellya",
    character: "Camellya",
    set: "BP01",
    imageId: "BP01-002",
    altImageIds: ["BP01-002_4"],
    level: 2,
    rarity: 3,
    weapon: "sword",
    element: "havoc",
    effects: [
      {
        condition: ["levelUp"],
        text: {
          th: "[Level up] นำการ์ดใบนี้กลับเข้า Character deck",
          en: "[Level up] Return this card to the Character deck",
        },
        resolve: (ctx) => ctx.returnToCharacterDeck(),
      },
      {
        condition: ["leader"],
        text: { th: "[Leader] แต่ละรอบการเล่น ดาเมจที่ได้รับ -1", en: "[Leader] Once per round, damage taken -1" },
        // "แต่ละรอบการเล่น" — once a round, so it softens the first hit and
        // is spent. Without the limit an unlimited red chain would have every
        // one of its hits cut, which is not what one line of text buys.
        resolve: (ctx) => ctx.modifyDamageTaken(-1, ctx.controllerId, "whileActive", { limit: 1 }),
      },
    ],
  }),
  defineCard({
    type: "leader",
    id: "BP01-010",
    name: "Shorekeeper",
    character: "Shorekeeper",
    set: "BP01",
    imageId: "BP01-010",
    altImageIds: ["BP01-010_2", "BP01-010_2PR"],
    level: 0,
    rarity: 1,
    weapon: "rectifier",
    element: "spectro",
    effects: [
      {
        condition: ["leader", "counter"],
        text: {
          th: "[Leader] [Counter] หาก counter ด้วยการ์ดสีเขียว สามารถแสดงการ์ด 1 ใบบนสุดของเด็ค จากนั้นนำขึ้นมือ",
          en: "[Leader] [Counter] If you counter with a green card, you may reveal the top card of your deck, then take it to hand",
        },
        resolve: (ctx) => {
          if (!(ctx.lastPlayedColor() === "green")) return;
          const revealed = ctx.revealTop(1);
          if (revealed.length === 0) return;
          if (ctx.confirm({
            th: "แสดงการ์ด 1 ใบบนสุดของเด็ค นำขึ้นมือไหม",
            en: "Reveal 1 from the top of your deck and take it?",
          })) ctx.deckToHand(1);
        },
      },
      {
        condition: ["leader", "judgement"],
        text: { th: "[Leader] [Judgement] หากชนะด้วยการ์ดสีเขียว ฟื้นฟูพลังชีวิต 1", en: "[Leader] [Judgement] If you win with a green card, heal 1 life" },
        resolve: (ctx) => {
          if (ctx.wonWith("green")) ctx.heal(1);
        },
      },
    ],
  }),
  defineCard({
    type: "leader",
    id: "BP01-011",
    name: "Encore",
    character: "Encore",
    set: "BP01",
    imageId: "BP01-011",
    altImageIds: ["BP01-011_4"],
    level: 2,
    rarity: 3,
    weapon: "rectifier",
    element: "fusion",
    effects: [
      {
        condition: ["passive"],
        text: { th: "การ์ดใบนี้สามารถเล่นได้จากความสามารถเท่านั้น", en: "This card can only be played by an ability" },
        resolve: (ctx) => ctx.log(`${ctx.self.name} enters play only through an ability`),
        tags: ["abilityOnly"],
      },
      {
        condition: ["passive"],
        text: { th: "การ์ดสีแดงของ 【Encore】 ได้รับ +1 ดาเมจ", en: "【Encore】's red cards gain +1 damage" },
        resolve: (ctx) => ctx.buff({ character: "Encore", color: "red" }, "attack", +1),
      },
      {
        condition: ["endTurn"],
        text: {
          th: "[At end of each turn]หากการ์ดใบนี้ไม่ได้ถูกลงในรอบนี้ นำการ์ดใบนี้กลับเข้า Charcater deck",
          en: "[At end of each turn] If this card wasn't played this round, return it to the Character deck",
        },
        resolve: (ctx) => {
          if (!ctx.selfPlayedThisTurn()) ctx.returnToCharacterDeck();
        },
      },
    ],
  }),
  defineCard({
    type: "leader",
    id: "BP01-029",
    name: "Jinshi",
    character: "Jinshi",
    set: "BP01",
    imageId: "BP01-029",
    altImageIds: ["BP01-029_2"],
    level: 1,
    rarity: 1,
    effects: [
      {
        condition: ["leader", "judgement"],
        text: { th: "[Leader] [Judgement] หากชนะด้วยการ์ดสีแดง ทำ 2 ดาเมจใส่ฝ่ายตรงข้าม", en: "[Leader] [Judgement] If you win with a red card, deal 2 damage to your opponent" },
        resolve: (ctx) => {
          if (ctx.wonWith("red")) ctx.damage(2);
        },
      },
    ],
  }),
  defineCard({
    type: "action",
    id: "BP01-047",
    name: "Burgeoning • Heavy Attack",
    character: "Camellya",
    set: "BP01",
    imageId: "BP01-047",
    altImageIds: ["BP01-047_2"],
    cost: 0,
    color: "red",
    speed: 6,
    attack: 1,
    rarity: 1,
    subtypes: ["Normal Attack", "Heavy Attack"],
    effects: [
      {
        condition: ["judgement"],
        text: { th: "[Judgement] หากชนะ จั่วการ์ด 1 ใบ", en: "[Judgement] If you win, draw 1 card" },
        resolve: (ctx) => {
          if (ctx.wonLastBattle()) ctx.draw(1);
        },
      },
    ],
  }),
  defineCard({
    type: "action",
    id: "BP01-051",
    name: "Vining Ronde",
    character: "Camellya",
    set: "BP01",
    imageId: "BP01-051",
    altImageIds: ["BP01-051_2"],
    cost: 0,
    color: "red",
    speed: 6,
    attack: 1,
    rarity: 1,
    subtypes: ["Basic Attack"],
    effects: [
      {
        condition: ["judgement"],
        text: { th: "[Judgement] หากชนะ จั่วการ์ด 1 ใบ", en: "[Judgement] If you win, draw 1 card" },
        resolve: (ctx) => {
          if (ctx.wonLastBattle()) ctx.draw(1);
        },
      },
    ],
  }),
  defineCard({
    type: "action",
    id: "BP01-053",
    name: "Origin Calculus • Dodge",
    character: "Shorekeeper",
    set: "BP01",
    imageId: "BP01-053",
    altImageIds: ["BP01-053_2"],
    cost: 0,
    color: "blue",
    speed: null,
    attack: 0,
    rarity: 1,
    subtypes: ["Dodge"],
    effects: [
      {
        condition: ["judgement"],
        text: { th: "[Judgement]หากชนะ ฟื้นฟู 1 พลังชีวิต", en: "[Judgement] If you win, heal 1 life" },
        resolve: (ctx) => {
          if (ctx.wonLastBattle()) ctx.heal(1);
        },
      },
    ],
  }),
  defineCard({
    type: "action",
    id: "BP01-058",
    name: "Supernal Stellarealm",
    character: "Shorekeeper",
    set: "BP01",
    imageId: "BP01-058",
    altImageIds: ["BP01-058_2"],
    cost: 0,
    color: "green",
    speed: 5,
    attack: 0,
    rarity: 1,
    effects: [
      {
        condition: ["judgement"],
        text: { th: "[Judgement] หากชนะ จั่วการ์ด 2 ใบ", en: "[Judgement] If you win, draw 2 cards" },
        resolve: (ctx) => {
          if (ctx.wonLastBattle()) ctx.draw(2);
        },
      },
      {
        // [Advantage] is printed on this one and was missing here, so the
        // ability fired on any loss instead of only while holding Advantage.
        condition: ["judgement", "advantage"],
        text: {
          th: "[Advantage] [Judgement] หากแพ้ด้วยการ์ดใบนี้ และหาก Leader เป็น Shorekeeper ในรอบนี้ ฝ่ายตรงข้ามไม่สามารถ Combo ได้",
          en: "[Advantage] [Judgement] If you lose with this card, and your Leader is Shorekeeper, your opponent cannot Combo this round",
        },
        resolve: (ctx) => {
            if (ctx.wonLastBattle()) return;
            if (ctx.leaderName() !== "Shorekeeper") return;
            ctx.restrict("noCombo", ctx.opponentId);
          },
      },
    ],
  }),
  defineCard({
    type: "action",
    id: "BP01-066",
    name: "Vibration Manifestation • Mid-air Attack",
    character: "Rover (F)",
    set: "BP01",
    imageId: "BP01-066",
    altImageIds: ["BP01-066_2"],
    cost: 0,
    color: "red",
    speed: 6,
    attack: 1,
    rarity: 1,
    subtypes: ["Normal Attack", "Mid-air Attack"],
    effects: [
      {
        condition: ["judgement"],
        text: { th: "[Judgement] หากชนะ จั่วการ์ด 1 ใบ", en: "[Judgement] If you win, draw 1 card" },
        resolve: (ctx) => {
          if (ctx.wonLastBattle()) ctx.draw(1);
        },
      },
    ],
  }),
  defineCard({
    type: "action",
    id: "BP01-068",
    name: "Vibration Manifestation • Mid-air Attack",
    character: "Rover (M)",
    set: "BP01",
    imageId: "BP01-068",
    altImageIds: ["BP01-068_2"],
    cost: 0,
    color: "red",
    speed: 6,
    attack: 1,
    rarity: 1,
    subtypes: ["Normal Attack", "Mid-air Attack"],
    effects: [
      {
        condition: ["judgement"],
        text: { th: "[Judgement] หากชนะ จั่วการ์ด 1 ใบ", en: "[Judgement] If you win, draw 1 card" },
        resolve: (ctx) => {
          if (ctx.wonLastBattle()) ctx.draw(1);
        },
      },
    ],
  }),
  defineCard({
    type: "action",
    id: "BP01-075",
    name: "Slash of Breaking Dawn • Heavy Attack",
    character: "Jinshi",
    set: "BP01",
    imageId: "BP01-075",
    altImageIds: ["BP01-075_2"],
    cost: 0,
    color: "red",
    speed: 5,
    attack: 1,
    rarity: 1,
    subtypes: ["Normal Attack", "Heavy Attack"],
    effects: [
      {
        condition: ["judgement"],
        text: { th: "[Judgement] หากชนะ จั่วการ์ด 1 ใบ", en: "[Judgement] If you win, draw 1 card" },
        resolve: (ctx) => {
          if (ctx.wonLastBattle()) ctx.draw(1);
        },
      },
    ],
  }),
  defineCard({
    type: "leader",
    id: "BP01-003",
    name: "Camellya",
    character: "Camellya",
    set: "BP01",
    imageId: "BP01-003",
    altImageIds: ["BP01-003_2"],
    level: 1,
    rarity: 1,
    weapon: "sword",
    element: "havoc",
    effects: [
      {
        condition: ["enter", "levelUp"],
        text: {
          th: "[Enter] / [Level up] สามารถนำการ์ด {Basic Attack} 1 ใบจากกองทิ้งขึ้นมือ",
          en: "[Enter] / [Level up] You may take 1 {Basic Attack} card from the trash to hand",
        },
        resolve: (ctx) => {
          // "สามารถ" — the player may decline, so ask before touching anything.
          const candidates = ctx
            .board()
            .trash.filter((c) => ctx.countMatching([c], { subtype: "Basic Attack" }) > 0);
          const picked = ctx.chooseCard(
            { th: "นำการ์ด {Basic Attack} 1 ใบจากกองทิ้งขึ้นมือไหม", en: "Return a Basic Attack card from the trash to hand?" },
            candidates,
            { optional: true }
          );
          if (picked) ctx.trashToHand(1, { cardId: picked.id });
        },
      },
    ],
  }),
  defineCard({
    type: "leader",
    id: "BP01-004",
    name: "Camellya",
    character: "Camellya",
    set: "BP01",
    imageId: "BP01-004",
    altImageIds: ["BP01-004_2"],
    level: 1,
    rarity: 1,
    weapon: "sword",
    element: "havoc",
    effects: [
      {
        condition: ["leader", "judgement"],
        text: {
          th: "[Leader] [Judgement] หากแพ้การ์ดสีฟ้า ในการเล่นการ์ดสีแดง สามารถแสดงการ์ด 1 ใบบนสุดของเด็ค จากนั้นนำขึ้นมือ",
          en: "[Leader] [Judgement] If a red card of yours loses to a blue card, you may reveal the top card of your deck, then take it to hand",
        },
        resolve: (ctx) => {
          if (!(ctx.lostTo("blue") && ctx.lastPlayedColor() === "red")) return;
          const revealed = ctx.revealTop(1);
          if (revealed.length === 0) return;
          if (ctx.confirm({
            th: "แสดงการ์ด 1 ใบบนสุดของเด็ค นำขึ้นมือไหม",
            en: "Reveal 1 from the top of your deck and take it?",
          })) ctx.deckToHand(1);
        },
      },
    ],
  }),
  defineCard({
    type: "leader",
    id: "BP01-005",
    name: "Camellya",
    character: "Camellya",
    set: "BP01",
    imageId: "BP01-005",
    altImageIds: ["BP01-005_2", "BP01-005_2PR"],
    level: 0,
    rarity: 1,
    weapon: "sword",
    element: "havoc",
    effects: [
      {
        condition: ["leader", "judgement"],
        text: {
          th: "[Leader] [Judgement] หากชนะ นำการ์ด {Basic attack} 1 ใบจากกองทิ้งขึ้นมือ",
          en: "[Leader] [Judgement] If you win, take 1 {Basic Attack} card from the trash to hand",
        },
        resolve: (ctx) => {
          if (!ctx.wonLastBattle()) return;
          ctx.trashToHand(1, { subtype: "Basic Attack" });
        },
      },
    ],
  }),
  defineCard({
    type: "leader",
    id: "BP01-006",
    name: "Shorekeeper",
    character: "Shorekeeper",
    set: "BP01",
    imageId: "BP01-006",
    altImageIds: ["BP01-006_4"],
    level: 2,
    rarity: 3,
    weapon: "rectifier",
    element: "spectro",
    effects: [
      {
        condition: ["passive"],
        text: {
          th: "2 ครั้งต่อรอบการเล่น หากฟื้นฟูพลังชีวิต สามารถจั่วการ์ด 1 ใบขึ้นมือ",
          en: "Up to twice per round, whenever you heal life, you may draw 1 card",
        },
        resolve: (ctx) => {
          // Only fires off a heal, and only twice a round.
          if (ctx.healedThisTurn() <= 0) return;
          if (!ctx.useLimit(2)) return;
          if (ctx.confirm({ th: "จั่วการ์ด 1 ใบไหม", en: "Draw a card?" })) ctx.draw(1);
        },
      },
    ],
  }),
  defineCard({
    type: "leader",
    id: "BP01-007",
    name: "Shorekeeper",
    character: "Shorekeeper",
    set: "BP01",
    imageId: "BP01-007",
    altImageIds: ["BP01-007_4", "BP01-007_5"],
    level: 2,
    rarity: 3,
    weapon: "rectifier",
    element: "spectro",
    effects: [
      {
        condition: ["leader", "counterPhaseStart"],
        text: {
          th: "[Leader] [At start of own Counter phase] \nหากบนมือมีการ์ด 4 ใบหรือต่ำกว่า จั่วให้มือมี 5 ใบ",
          en: "[Leader] [At start of own Counter phase] \nIf you have 4 or fewer cards in hand, draw up to 5",
        },
        resolve: (ctx) => {
            const missing = 5 - ctx.hand().length;
            if (missing > 0) ctx.draw(missing);
          },
      },
    ],
  }),
  defineCard({
    type: "action",
    id: "BP01-076",
    name: "Freezing Thorns",
    character: "Sanhua",
    set: "BP01",
    imageId: "BP01-076",
    altImageIds: ["BP01-076_2"],
    cost: 1,
    color: "blue",
    speed: null,
    attack: 0,
    rarity: 1,
    subtypes: ["Dodge"],
    effects: [
      {
        condition: ["counter"],
        text: { th: "[Counter] สามารถเปลี่ยน Leader เป็น Sanhua", en: "[Counter] You may switch your Leader to Sanhua" },
        resolve: (ctx) => {
            if (ctx.confirm({ th: "เปลี่ยน Leader เป็น Sanhua ไหม", en: "Switch your Leader to Sanhua?" })) {
              ctx.switchLeaderTo("Sanhua");
            }
          },
      },
      {
        condition: ["judgement"],
        text: {
          th: "[Judgement] หากชนะและมี Leader เป็น Sanhua Level up ให้ Sanhua ของเจ้าของ",
          en: "[Judgement] If you win and your Leader is Sanhua, level up your Sanhua",
        },
        resolve: (ctx) => {
            if (ctx.wonLastBattle() && ctx.leaderName() === "Sanhua") ctx.levelUpCharacter("Sanhua");
          },
      },
    ],
  }),
  defineCard({
    type: "leader",
    id: "BP01-008",
    name: "Shorekeeper",
    character: "Shorekeeper",
    set: "BP01",
    imageId: "BP01-008",
    altImageIds: ["BP01-008_2"],
    level: 1,
    rarity: 1,
    weapon: "rectifier",
    element: "spectro",
    effects: [
      {
        condition: ["switch"],
        text: { th: "[Switch] สามารถจั่วการ์ด 1 ใบ จากนั้นทิ้งการ์ด 1 ใบ", en: "[Switch] You may draw 1 card, then discard 1 card" },
        resolve: (ctx) => {
            if (!ctx.confirm({ th: "จั่ว 1 ใบแล้วทิ้ง 1 ใบไหม", en: "Draw a card, then discard one?" })) return;
            ctx.draw(1);
            const pick = ctx.chooseCard({ th: "เลือกการ์ดที่จะทิ้ง", en: "Discard which card?" }, ctx.hand());
            if (pick) ctx.discardCards([pick]);
          },
      },
    ],
  }),
  defineCard({
    type: "leader",
    id: "BP01-009",
    name: "Shorekeeper",
    character: "Shorekeeper",
    set: "BP01",
    imageId: "BP01-009",
    altImageIds: ["BP01-009_2"],
    level: 1,
    rarity: 1,
    weapon: "rectifier",
    element: "spectro",
    effects: [
      {
        condition: ["enter", "levelUp"],
        text: {
          th: "[Enter] / [Level up] สามารถนำการ์ด {Intro Skill} 1 ใบจากกองทิ้งขึ้นมือ",
          en: "[Enter] / [Level up] You may take 1 {Intro Skill} card from the trash to hand",
        },
        resolve: (ctx) => {
          // "สามารถ" — the player may decline, so ask before touching anything.
          const candidates = ctx
            .board()
            .trash.filter((c) => ctx.countMatching([c], { subtype: "Intro Skill" }) > 0);
          const picked = ctx.chooseCard(
            { th: "นำการ์ด {Intro Skill} 1 ใบจากกองทิ้งขึ้นมือไหม", en: "Return a Intro Skill card from the trash to hand?" },
            candidates,
            { optional: true }
          );
          if (picked) ctx.trashToHand(1, { cardId: picked.id });
        },
      },
    ],
  }),
  defineCard({
    type: "leader",
    id: "BP01-012",
    name: "Encore",
    character: "Encore",
    set: "BP01",
    imageId: "BP01-012",
    altImageIds: ["BP01-012_4", "BP01-012_5"],
    level: 2,
    rarity: 1,
    weapon: "rectifier",
    element: "fusion",
    effects: [
      {
        condition: ["leader", "endTurn"],
        text: {
          th: "[Leader] [At end of each turn] หากฝ่ายตรงข้ามได้รับดาเมจในรอบนี้ นำการ์ดของ Encore 1 ใบจากกองทิ้งขึ้นมือ",
          en: "[Leader] [At end of each turn] If your opponent took damage this round, take 1 Encore card from the trash to hand",
        },
        resolve: (ctx) => {
          if (ctx.damageTakenThisTurn(ctx.opponentId) > 0) {
            ctx.trashToHand(1, { character: "Encore" });
          }
        },
      },
    ],
  }),
  defineCard({
    type: "leader",
    id: "BP01-013",
    name: "Encore",
    character: "Encore",
    set: "BP01",
    imageId: "BP01-013",
    altImageIds: ["BP01-013_2"],
    level: 1,
    rarity: 1,
    weapon: "rectifier",
    element: "fusion",
    effects: [
      {
        condition: ["enter", "levelUp"],
        text: {
          th: "[Enter] / [Level up] นำการ์สีแดงของ Encore 1 ใบจากกองทิ้งขึ้นมือ",
          en: "[Enter] / [Level up] Take 1 of Encore's red cards from the trash to hand",
        },
        resolve: (ctx) => ctx.trashToHand(1, { character: "Encore", color: "red" }),
      },
    ],
  }),
  defineCard({
    type: "leader",
    id: "BP01-014",
    name: "Encore",
    character: "Encore",
    set: "BP01",
    imageId: "BP01-014",
    altImageIds: ["BP01-014_2"],
    level: 1,
    rarity: 1,
    weapon: "rectifier",
    element: "fusion",
    grants: {
      // Handed to Encore's {Heavy Attack} and {Forte Circuit} cards while
      // this Leader is out. It resolves on the card that received it, so
      // `ctx.self` there is that card, not this one.
      revenge: {
        condition: ["counterPhaseEnd"],
        text: {
          th: "หากแพ้การ์ดสีแดงในการเล่นการ์ดใบนี้ ทำดาเมจเท่ากับดาเมจของการ์ดใบนี้แก่ฝ่ายตรงข้าม",
          en: "If this card lost to a red card, deal damage equal to its own damage.",
        },
        resolve: (ctx) => {
          if (!ctx.lostTo("red")) return;
          if (ctx.self.type !== "action") return;
          ctx.damage(ctx.self.attack);
        },
      },
    },
    effects: [
      {
        condition: ["leader", "judgement"],
        text: {
          th: "[Leader] การ์ด {Heavy Attack} และ {Forte Circuit} ของ Encore ได้รับ “[Judgement] หากแพ้การ์ดสีแดงในการเล่นการ์ดใบนี้ หลังจบช่วง Counter ทำดาเมจเท่ากับดาเมจของการ์ดใบนี้แก่ฝ่ายตรงข้าม”",
          en: "[Leader] Encore's {Heavy Attack} and {Forte Circuit} cards gain “[Judgement] If this card lost to a red card, after the Counter phase ends, deal damage to your opponent equal to this card's damage”",
        },
        resolve: (ctx) => {
            // The ability is handed to the cards themselves, so it fires from
            // whichever one is actually played.
            ctx.grantEffect(
              { character: "Encore", subtype: ["Heavy Attack", "Forte Circuit"] },
              "revenge",
              "whileActive"
            );
          },
      },
    ],
  }),
  defineCard({
    type: "leader",
    id: "BP01-015",
    name: "Encore",
    character: "Encore",
    set: "BP01",
    imageId: "BP01-015",
    altImageIds: ["BP01-015_2", "BP01-015_2PR"],
    level: 0,
    rarity: 1,
    weapon: "rectifier",
    element: "fusion",
    effects: [
      {
        condition: ["leader"],
        text: {
          th: "[Leader] แต่ละรอบ การ์ด {Normal attack} ใบแรกของ Encore ได้รับ +2 ดาเมจ",
          en: "[Leader] Once per round, Encore's first {Normal Attack} card gains +2 damage",
        },
        resolve: (ctx) =>
            ctx.buff({ character: "Encore", subtype: "Normal Attack" }, "attack", 2, "turn", {
              limit: 1,
            }),
      },
    ],
  }),
  defineCard({
    type: "leader",
    id: "BP01-016",
    name: "Rover (F)",
    character: "Rover (F)",
    set: "BP01",
    imageId: "BP01-016",
    altImageIds: ["BP01-016_4", "BP01-016_4", "BP01-016_5"],
    level: 2,
    rarity: 3,
    weapon: "sword",
    element: "spectro",
    effects: [
      {
        condition: ["leader", "judgement"],
        text: {
          th: "[Leader] [Judgement] หากชนะการ์ดสีฟ้าด้วยการ์ดสีเขียว ถ้ามีการ์ดในมือไม่ถึง 8 ใบ จั่วการ์ดให้เป็น 8 ใบ",
          en: "[Leader] [Judgement] If you beat a blue card with a green card, and you have fewer than 8 cards in hand, draw up to 8",
        },
        resolve: (ctx) => {
            if (!ctx.wonWith("green")) return;
            if (ctx.lastPlayedColor(ctx.opponentId) !== "blue") return;
            const missing = 8 - ctx.hand().length;
            if (missing > 0) ctx.draw(missing);
          },
      },
    ],
  }),
  defineCard({
    type: "leader",
    id: "BP01-017",
    name: "Rover (F)",
    character: "Rover (F)",
    set: "BP01",
    imageId: "BP01-017",
    altImageIds: ["BP01-017_2"],
    level: 1,
    rarity: 1,
    weapon: "sword",
    element: "spectro",
    effects: [
      {
        condition: ["enter", "levelUp"],
        text: {
          th: "[Enter] / [Level up] แสดงการ์ด 1 ใบบนสุดของเด็ค สามารถนำการ์ดใบนี้ขึ้นมือได้",
          en: "[Enter] / [Level up] Reveal the top card of your deck; you may take it to hand",
        },
        resolve: (ctx) => {
          const revealed = ctx.revealTop(1);
          if (revealed.length === 0) return;
          if (ctx.confirm({
            th: "แสดงการ์ด 1 ใบบนสุดของเด็ค นำขึ้นมือไหม",
            en: "Reveal 1 from the top of your deck and take it?",
          })) ctx.deckToHand(1);
        },
      },
    ],
  }),
  defineCard({
    type: "leader",
    id: "BP01-019",
    name: "Rover (M)",
    character: "Rover (M)",
    set: "BP01",
    imageId: "BP01-019",
    altImageIds: ["BP01-019_4", "BP01-019_4", "BP01-019_5"],
    level: 2,
    rarity: 3,
    weapon: "sword",
    element: "spectro",
    effects: [
      {
        condition: ["leader", "judgement", "follow"],
        followCount: 3,
        text: {
          th: "[Leader] [Judgement] หากชนะด้วยการ์ดสีเขียว ได้รับ +3 [Follow-up attack]",
          en: "[Leader] [Judgement] If you win with a green card, gain +3 [Follow-up attack]",
        },
        resolve: (ctx) => { if (ctx.wonWith("green")) ctx.grantFollowUp(3); },
      },
    ],
  }),
  defineCard({
    type: "leader",
    id: "BP01-020",
    name: "Rover (M)",
    character: "Rover (M)",
    set: "BP01",
    imageId: "BP01-020",
    altImageIds: ["BP01-020_2"],
    level: 1,
    rarity: 1,
    weapon: "sword",
    element: "spectro",
    effects: [
      {
        condition: ["enter", "levelUp"],
        text: {
          th: "[Enter] / [Level up] แสดงการ์ด 1 ใบบนสุดของเด็ค สามารถนำการ์ดใบนี้ขึ้นมือได้",
          en: "[Enter] / [Level up] Reveal the top card of your deck; you may take it to hand",
        },
        resolve: (ctx) => {
          const revealed = ctx.revealTop(1);
          if (revealed.length === 0) return;
          if (ctx.confirm({
            th: "แสดงการ์ด 1 ใบบนสุดของเด็ค นำขึ้นมือไหม",
            en: "Reveal 1 from the top of your deck and take it?",
          })) ctx.deckToHand(1);
        },
      },
    ],
  }),
  defineCard({
    type: "leader",
    id: "BP01-022",
    name: "Yangyang",
    character: "Yangyang",
    set: "BP01",
    imageId: "BP01-022",
    altImageIds: ["BP01-022_4", "BP01-022_5"],
    level: 2,
    rarity: 3,
    weapon: "sword",
    element: "aero",
    effects: [
      {
        condition: ["endTurn"],
        text: {
          th: "[At end of own turn] ทิ้งการ์ด 1 ใบ หากทำสลับ Leader เป็น Yangyang",
          en: "[At end of own turn] You may discard 1 card; if you do, switch your Leader to Yangyang",
        },
        resolve: (ctx) => {
            if (ctx.hand().length === 0) return;
            const pick = ctx.chooseCard(
              { th: "ทิ้งการ์ด 1 ใบเพื่อสลับ Leader เป็น Yangyang", en: "Discard a card to switch to Yangyang?" },
              ctx.hand(),
              { optional: true }
            );
            if (!pick) return;
            ctx.discardCards([pick]);
            ctx.switchLeaderTo("Yangyang");
          },
      },
    ],
  }),
  defineCard({
    type: "leader",
    id: "BP01-023",
    name: "Yangyang",
    character: "Yangyang",
    set: "BP01",
    imageId: "BP01-023",
    altImageIds: ["BP01-023_2"],
    level: 1,
    rarity: 1,
    weapon: "sword",
    element: "aero",
    effects: [
      {
        condition: ["enter", "levelUp"],
        text: {
          th: "[Enter] / [Level up] สามารถนำการ์ดใบบนสุดของเด็ควางที่ Concerto area",
          en: "[Enter] / [Level up] You may put the top card of your deck into the Concerto area",
        },
        resolve: (ctx) => {
          if (ctx.board().actionDeck.length === 0) return;
          if (
            ctx.confirm({
              th: "นำการ์ด 1 ใบบนสุดของเด็ควางที่ Concerto Area ไหม",
              en: "Put 1 from the top of your deck into the Concerto area?",
            })
          ) {
            ctx.topToConcerto(1);
          }
        },
      },
    ],
  }),
  defineCard({
    type: "leader",
    id: "BP01-025",
    name: "Chixia",
    character: "Chixia",
    set: "BP01",
    imageId: "BP01-025",
    altImageIds: ["BP01-025_4", "BP01-025_5"],
    level: 2,
    rarity: 3,
    weapon: "pistols",
    element: "fusion",
    effects: [
      {
        condition: ["leader", "counterPhaseEnd"],
        text: {
          th: "[Leader] [At end of Counter phase] หากใน Action area ของเจ้าของมีการ์ด {Normal Attack} 2 ใบหรือมากกว่า ทำ 3 ดาเมจใส่ฝ่ายตรงข้าม",
          en: "[Leader] [At end of Counter phase] If your Action area has 2 or more {Normal Attack} cards, deal 3 damage to your opponent",
        },
        resolve: (ctx) => {
          const normals = ctx.countMatching(ctx.actionZone(), { subtype: "Normal Attack" });
          if (normals >= 2) ctx.damage(3);
        },
      },
    ],
  }),
  defineCard({
    type: "leader",
    id: "BP01-026",
    name: "Chixia",
    character: "Chixia",
    set: "BP01",
    imageId: "BP01-026",
    altImageIds: ["BP01-026_2"],
    level: 1,
    rarity: 1,
    weapon: "pistols",
    element: "fusion",
    effects: [
      {
        condition: ["enter", "levelUp"],
        text: {
          th: "[Enter] / [Level up] สามารถนำการ์ด {Normal Attack} 1 ใบจากกองทิ้งขึ้นมือ",
          en: "[Enter] / [Level up] You may take 1 {Normal Attack} card from the trash to hand",
        },
        resolve: (ctx) => {
          // "สามารถ" — the player may decline, so ask before touching anything.
          const candidates = ctx
            .board()
            .trash.filter((c) => ctx.countMatching([c], { subtype: "Normal Attack" }) > 0);
          const picked = ctx.chooseCard(
            { th: "นำการ์ด {Normal Attack} 1 ใบจากกองทิ้งขึ้นมือไหม", en: "Return a Normal Attack card from the trash to hand?" },
            candidates,
            { optional: true }
          );
          if (picked) ctx.trashToHand(1, { cardId: picked.id });
        },
      },
    ],
  }),
  defineCard({
    type: "leader",
    id: "BP01-028",
    name: "Jinshi",
    character: "Jinshi",
    set: "BP01",
    imageId: "BP01-028",
    altImageIds: ["BP01-028_4", "BP01-028_5"],
    level: 2,
    rarity: 3,
    weapon: "sword",
    element: "spectro",
    effects: [
      {
        condition: ["leader", "judgement"],
        text: {
          th: "[Leader] [Judgement] หากชนะในรอบของเจ้าของ แสดงการ์ด 5 ใบบนสุดของเด็ค นำการ์ดของ 【Jinshi】 ทั้งหมดขึ้นมือ จากนั้นนำการ์ดที่เหลือลงกองทิ้ง",
          en: "[Leader] [Judgement] If you win on your own turn, reveal the top 5 cards of your deck, take all 【Jinshi】 cards among them to hand, then discard the rest",
        },
        resolve: (ctx) => {
            if (!ctx.wonLastBattle()) return;
            // Revealing, not drawing: with 2 cards left this sees 2, and the
            // deck is rebuilt after the skill finishes rather than part-way
            // through it — so a thin deck does not turn this into "take 5".
            const top = ctx.deckToHand(5);
            const others = top.filter((c) => ctx.countMatching([c], { character: "Jinshi" }) === 0);
            ctx.discardCards(others);
          },
      },
    ],
  }),
  defineCard({
    type: "leader",
    id: "BP01-031",
    name: "Sanhua",
    character: "Sanhua",
    set: "BP01",
    imageId: "BP01-031",
    altImageIds: ["BP01-031_4", "BP01-031_4", "BP01-031_5"],
    level: 2,
    rarity: 3,
    weapon: "sword",
    element: "glacio",
    effects: [
      {
        condition: ["leader", "judgement", "follow"],
        followCount: 3,
        text: {
          th: "[Leader] [Judgement] หากชนะด้วยการ์ดสีฟ้า สามารถเปลี่ยนลีดเดอร์และได้รับ +3[follow-up attack]",
          en: "[Leader] [Judgement] If you win with a blue card, you may switch Leaders and gain +3 [follow-up attack]",
        },
        resolve: (ctx) => {
            if (!ctx.wonWith("blue")) return;
            const back = ctx.board().back;
            if (back.length > 0) {
              const chosen = ctx.chooseOption(
                { th: "สลับ Leader ไปตัวไหน", en: "Switch your Leader to?" },
                [
                  ...back.map((slot) => ({ value: slot.card.name, label: { th: slot.card.name, en: slot.card.name } })),
                  { value: "", label: { th: "ไม่สลับ", en: "Do not switch" } },
                ]
              );
              if (chosen) ctx.switchLeaderTo(chosen);
            }
            ctx.grantFollowUp(3);
          },
      },
    ],
  }),
  defineCard({
    type: "leader",
    id: "BP01-032",
    name: "Sanhua",
    character: "Sanhua",
    set: "BP01",
    imageId: "BP01-032",
    altImageIds: ["BP01-032_2"],
    level: 1,
    rarity: 1,
    weapon: "sword",
    element: "glacio",
    effects: [
      {
        condition: ["enter", "levelUp"],
        text: {
          th: "[Enter] / [Level up] สามารถนำการ์ดจากกองทิ้ง 1 ใบวางที่ Concerto area",
          en: "[Enter] / [Level up] You may put 1 card from the trash into the Concerto area",
        },
        resolve: (ctx) => {
            const pick = ctx.chooseCard(
              { th: "นำการ์ดจากกองทิ้งไปวางที่ Concerto area", en: "Put a card from the trash into the Concerto area?" },
              ctx.board().trash,
              { optional: true }
            );
            if (pick) ctx.trashToConcerto(1, { cardId: pick.id });
          },
      },
    ],
  }),
  defineCard({
    type: "action",
    id: "BP01-034",
    name: "Traffic Illuminator",
    character: null,
    set: "BP01",
    imageId: "BP01-034",
    altImageIds: ["BP01-034_2"],
    cost: 0,
    color: "red",
    speed: 5,
    attack: 1,
    rarity: 1,
    subtypes: ["Echo", "Molten Rift"],
    effects: [
      {
        condition: ["passive"],
        text: { th: "การ์ด〈Echo〉สามารถอยู่บน Action Area ได้สูงสุด 1 ใบ", en: "At most 1 〈Echo〉 card may be in the Action Area" },
        resolve: (ctx) => ctx.limitActionArea({ subtype: "Echo" }, 1),
      },
      {
        condition: ["passive"],
        text: {
          th: "หากใน Concerto Area มีการ์ด〈Molten Rift〉2 ใบ หรือมากกว่ารวมการ์ดใบนี้ การ์ด〈Fusion〉ใบแรกที่ใช้ได้รับ +1 ดาเมจ",
          en: "If the Concerto Area has 2 or more 〈Molten Rift〉 cards including this one, the first 〈Fusion〉 card played gains +1 damage",
        },
        resolve: (ctx) => {
            if (ctx.countMatching(ctx.concerto(), { subtype: "Molten Rift" }) < 2) return;
            ctx.buff({ subtype: "Fusion" }, "attack", 1, "turn", { limit: 1 });
          },
      },
    ],
  }),
  defineCard({
    type: "action",
    id: "BP01-035",
    name: "Inferno Rider",
    character: null,
    set: "BP01",
    imageId: "BP01-035",
    altImageIds: ["BP01-035_2"],
    cost: 1,
    color: "red",
    speed: 5,
    attack: 2,
    rarity: 1,
    subtypes: ["Echo", "Molten Rift"],
    effects: [
      {
        condition: ["passive"],
        text: { th: "การ์ด〈Echo〉สามารถอยู่บน Action Area ได้สูงสุด 1 ใบ", en: "At most 1 〈Echo〉 card may be in the Action Area" },
        resolve: (ctx) => ctx.limitActionArea({ subtype: "Echo" }, 1),
      },
      {
        condition: ["judgement", "advantage"],
        text: {
          th: "[Advantage] หากสร้างความเสียหายแก่ฝ่ายตรงข้าม ทุกๆการ์ด 4 ใบในมือของฝ่ายตรงข้าม ฝ่ายตรงข้ามทิ้งการ์ด 1 ใบในมือ",
          en: "[Advantage] If you deal damage to your opponent, for every 4 cards in their hand, they discard 1 card",
        },
        resolve: (ctx) => {
            // "when you deal damage" is THIS card's damage: another card of
            // ours winning the clash does not set this off.
            if (!ctx.wonWithThisCard()) return;
            ctx.discard(Math.floor(ctx.hand(ctx.opponentId).length / 4), ctx.opponentId);
          },
      },
    ],
  }),
  defineCard({
    type: "action",
    id: "BP01-036",
    name: "Gulpuff",
    character: null,
    set: "BP01",
    imageId: "BP01-036",
    altImageIds: ["BP01-036_2"],
    cost: 0,
    color: "red",
    speed: 5,
    attack: 1,
    rarity: 1,
    subtypes: ["Echo", "Freezing Frost"],
    effects: [
      {
        condition: ["passive"],
        text: { th: "การ์ด〈Echo〉สามารถอยู่บน Action Area ได้สูงสุด 1 ใบ", en: "At most 1 〈Echo〉 card may be in the Action Area" },
        resolve: (ctx) => ctx.limitActionArea({ subtype: "Echo" }, 1),
      },
      {
        condition: ["passive"],
        text: {
          th: "หากใน Concerto Area มีการ์ด〈Freezing Frost〉2 ใบ หรือมากกว่ารวมการ์ดใบนี้ การ์ด〈Glacio〉ใบแรกที่ใช้ได้รับ +1 ดาเมจ",
          en: "If the Concerto Area has 2 or more 〈Freezing Frost〉 cards including this one, the first 〈Glacio〉 card played gains +1 damage",
        },
        resolve: (ctx) => {
            if (ctx.countMatching(ctx.concerto(), { subtype: "Freezing Frost" }) < 2) return;
            ctx.buff({ subtype: "Glacio" }, "attack", 1, "turn", { limit: 1 });
          },
      },
    ],
  }),
  defineCard({
    type: "action",
    id: "BP01-037",
    name: "Lampylumen Myriad",
    character: null,
    set: "BP01",
    imageId: "BP01-037",
    altImageIds: ["BP01-037_2"],
    cost: 1,
    color: "red",
    speed: 5,
    attack: 2,
    rarity: 1,
    subtypes: ["Echo", "Freezing Frost"],
    effects: [
      {
        condition: ["passive"],
        text: { th: "การ์ด 〈Echo〉สามารถอยู่บน Action Area ได้สูงสุด 1 ใบ", en: "At most 1 〈Echo〉 card may be in the Action Area" },
        resolve: (ctx) => ctx.limitActionArea({ subtype: "Echo" }, 1),
      },
      {
        condition: ["judgement", "advantage"],
        text: {
          th: "[Advantage] หากสร้างความเสียหายแก่ฝ่ายตรงข้าม นำการ์ด 1 ใบใน Concerto Area ของฝ่ายตรงข้ามลงกองทิ้ง",
          en: "[Advantage] If you deal damage to your opponent, put 1 card from their Concerto Area into the trash",
        },
        resolve: (ctx) => {
            // "when you deal damage" is THIS card's damage, not any win.
            if (ctx.wonWithThisCard()) ctx.concertoToTrash(1, undefined, ctx.opponentId);
          },
      },
    ],
  }),
  defineCard({
    type: "action",
    id: "BP01-038",
    name: "Chirpuff",
    character: null,
    set: "BP01",
    imageId: "BP01-038",
    altImageIds: ["BP01-038_2"],
    cost: 0,
    color: "red",
    speed: 5,
    attack: 1,
    rarity: 1,
    subtypes: ["Echo", "Sierra Gale"],
    effects: [
      {
        condition: ["passive"],
        text: { th: "การ์ด 〈Echo〉สามารถอยู่บน Action Area ได้สูงสุด 1 ใบ", en: "At most 1 〈Echo〉 card may be in the Action Area" },
        resolve: (ctx) => ctx.limitActionArea({ subtype: "Echo" }, 1),
      },
      {
        condition: ["passive"],
        text: {
          th: "หากใน Concerto Area มีการ์ด〈Sierra Gale〉2 ใบ หรือมากกว่ารวมการ์ดใบนี้ การ์ด〈Aero〉ใบแรกที่ใช้ได้รับ +1 ดาเมจ",
          en: "If the Concerto Area has 2 or more 〈Sierra Gale〉 cards including this one, the first 〈Aero〉 card played gains +1 damage",
        },
        resolve: (ctx) => {
            if (ctx.countMatching(ctx.concerto(), { subtype: "Sierra Gale" }) < 2) return;
            ctx.buff({ subtype: "Aero" }, "attack", 1, "turn", { limit: 1 });
          },
      },
    ],
  }),
  defineCard({
    type: "action",
    id: "BP01-039",
    name: "Feilian Beringal",
    character: null,
    set: "BP01",
    imageId: "BP01-039",
    altImageIds: ["BP01-039_2"],
    cost: 1,
    color: "red",
    speed: 5,
    attack: 2,
    rarity: 1,
    subtypes: ["Echo", "Sierra Gale"],
    effects: [
      {
        condition: ["passive"],
        text: { th: "การ์ด 〈Echo〉สามารถอยู่บน Action Area ได้สูงสุด 1 ใบ", en: "At most 1 〈Echo〉 card may be in the Action Area" },
        resolve: (ctx) => ctx.limitActionArea({ subtype: "Echo" }, 1),
      },
      {
        condition: ["judgement", "advantage"],
        text: {
          th: "[Advantage] หากสร้างความเสียหายแก่ฝ่ายตรงข้าม สุ่มการ์ด 1 ใบในมือฝ่ายตรงข้ามลงไปไว้ใต้ Action deck ของฝ่ายตรงข้าม",
          en: "[Advantage] If you deal damage to your opponent, put 1 random card from their hand on the bottom of their Action deck",
        },
        resolve: (ctx) => {
            // "when you deal damage" is THIS card's damage, not any win.
            if (!ctx.wonWithThisCard()) return;
            const picked = ctx.randomFromHand(ctx.opponentId);
            if (picked) ctx.toDeckBottom([picked], ctx.opponentId);
          },
      },
    ],
  }),
  defineCard({
    type: "action",
    id: "BP01-040",
    name: "Roseshroom",
    character: null,
    set: "BP01",
    imageId: "BP01-040",
    altImageIds: ["BP01-040_2"],
    cost: 0,
    color: "red",
    speed: 5,
    attack: 1,
    rarity: 1,
    subtypes: ["Echo", "Havoc Eclipse"],
    effects: [
      {
        condition: ["passive"],
        text: { th: "การ์ด 〈Echo〉สามารถอยู่บน Action Area ได้สูงสุด 1 ใบ", en: "At most 1 〈Echo〉 card may be in the Action Area" },
        resolve: (ctx) => ctx.limitActionArea({ subtype: "Echo" }, 1),
      },
      {
        condition: ["passive"],
        text: {
          th: "หากใน Concerto Area มีการ์ด 〈Havoc Eclipse〉 2 ใบ หรือมากกว่ารวมการ์ดใบนี้ การ์ด 〈Havoc〉ใบแรกที่ใช้ได้รับ +1 ดาเมจ",
          en: "If the Concerto Area has 2 or more 〈Havoc Eclipse〉 cards including this one, the first 〈Havoc〉 card played gains +1 damage",
        },
        resolve: (ctx) => {
            if (ctx.countMatching(ctx.concerto(), { subtype: "Havoc Eclipse" }) < 2) return;
            ctx.buff({ subtype: "Havoc" }, "attack", 1, "turn", { limit: 1 });
          },
      },
    ],
  }),
  defineCard({
    type: "action",
    id: "BP01-041",
    name: "Crownless",
    character: null,
    set: "BP01",
    imageId: "BP01-041",
    altImageIds: ["BP01-041_2"],
    cost: 1,
    color: "red",
    speed: 5,
    attack: 2,
    rarity: 1,
    subtypes: ["Echo", "Havoc Eclipse"],
    effects: [
      {
        condition: ["passive"],
        text: { th: "การ์ด 〈Echo〉สามารถอยู่บน Action Area ได้สูงสุด 1 ใบ", en: "At most 1 〈Echo〉 card may be in the Action Area" },
        resolve: (ctx) => ctx.limitActionArea({ subtype: "Echo" }, 1),
      },
      {
        condition: ["judgement", "advantage"],
        text: {
          th: "[Advantage] หากสร้างความเสียหายแก่ฝ่ายตรงข้าม นำการ์ด 3 ใบบนสุดของเด็คฝ่ายตรงข้ามตรงข้ามลงกองทิ้ง",
          en: "[Advantage] If you deal damage to your opponent, put the top 3 cards of their deck into the trash",
        },
        resolve: (ctx) => {
            // "when you deal damage" is THIS card's damage, not any win.
            if (ctx.wonWithThisCard()) ctx.deckToTrash(3, ctx.opponentId);
          },
      },
    ],
  }),
  defineCard({
    type: "action",
    id: "BP01-042",
    name: "Cruisewing",
    character: null,
    set: "BP01",
    imageId: "BP01-042",
    altImageIds: ["BP01-042_2"],
    cost: 1,
    color: "red",
    speed: 5,
    attack: 2,
    rarity: 1,
    subtypes: ["Echo", "Celestial Light"],
    effects: [
      {
        condition: ["passive"],
        text: { th: "การ์ด 〈Echo〉สามารถอยู่บน Action Area ได้สูงสุด 1 ใบ", en: "At most 1 〈Echo〉 card may be in the Action Area" },
        resolve: (ctx) => ctx.limitActionArea({ subtype: "Echo" }, 1),
      },
      {
        condition: ["passive"],
        text: {
          th: "หากใน Concerto Area มีการ์ด 〈Celestial Light〉2 ใบ หรือมากกว่ารวมการ์ดใบนี้ การ์ด 〈Spectro〉 ใบแรกที่ใช้ได้รับ +1 ดาเมจ",
          en: "If the Concerto Area has 2 or more 〈Celestial Light〉 cards including this one, the first 〈Spectro〉 card played gains +1 damage",
        },
        resolve: (ctx) => {
          if (ctx.countMatching(ctx.concerto(), { subtype: "Celestial Light" }) < 2) return;
          ctx.buff({ subtype: "Spectro" }, "attack", 1, "turn", { limit: 1 });
        },
      },
    ],
  }),
  defineCard({
    type: "action",
    id: "BP01-043",
    name: "Mourning Aix",
    character: null,
    set: "BP01",
    imageId: "BP01-043",
    altImageIds: ["BP01-043_2"],
    cost: 1,
    color: "red",
    speed: 5,
    attack: 2,
    rarity: 1,
    subtypes: ["Echo", "Celestial Light"],
    effects: [
      {
        condition: ["passive"],
        text: { th: "การ์ด 〈Echo〉สามารถอยู่บน Action Area ได้สูงสุด 1 ใบ", en: "At most 1 〈Echo〉 card may be in the Action Area" },
        resolve: (ctx) => ctx.limitActionArea({ subtype: "Echo" }, 1),
      },
      {
        condition: ["judgement", "advantage"],
        text: {
          th: "[Advantage] หากสร้างความเสียหายแก่ฝ่ายตรงข้าม นำการ์ด 2 ใบจากกองทิ้งฝ่ายตรงข้าม นำไปไว้ใต้ Action deck ของฝ่ายตรงข้าม",
          en: "[Advantage] If you deal damage to your opponent, put 2 cards from their trash on the bottom of their Action deck",
        },
        resolve: (ctx) => {
            // "when you deal damage" is THIS card's damage, not any win.
            if (!ctx.wonWithThisCard()) return;
            ctx.toDeckBottom(ctx.board(ctx.opponentId).trash.slice(-2), ctx.opponentId);
          },
      },
    ],
  }),
  defineCard({
    type: "action",
    id: "BP01-044",
    name: "Burgeoning • Basic Attack",
    character: "Camellya",
    set: "BP01",
    imageId: "BP01-044",
    altImageIds: ["BP01-044_2"],
    cost: 0,
    color: "red",
    speed: 8,
    attack: 1,
    rarity: 1,
    subtypes: ["Normal Attack", "Basic Attack"],
    effects: [],
  }),
  defineCard({
    type: "action",
    id: "BP01-045",
    name: "Burgeoning • Dodge Counter",
    character: "Camellya",
    set: "BP01",
    imageId: "BP01-045",
    altImageIds: ["BP01-045_2"],
    cost: 0,
    color: "blue",
    speed: null,
    attack: 3,
    rarity: 1,
    subtypes: ["Dodge Counter"],
    effects: [],
  }),
  defineCard({
    type: "action",
    id: "BP01-046",
    name: "Everblooming",
    character: "Camellya",
    set: "BP01",
    imageId: "BP01-046",
    cost: 0,
    color: "red",
    speed: 0,
    attack: 0,
    rarity: 1,
    subtypes: ["Intro Skill"],
    effects: [
      {
        condition: ["combo"],
        text: {
          th: "[Combo] เปลี่ยน Leader หาก Camellya เป็นตัวที่ถูกสลับ Level up ให้「Camellya」 ของคุณ",
          en: "[Combo] Switch Leaders; if 「Camellya」 is one of the switched characters, level up your 「Camellya」",
        },
        resolve: (ctx) => {
            const back = ctx.board().back;
            if (back.length === 0) return;
            const chosen = ctx.chooseOption(
              { th: "สลับ Leader ไปตัวไหน", en: "Switch your Leader to?" },
              [
                ...back.map((slot) => ({ value: slot.card.name, label: { th: slot.card.name, en: slot.card.name } })),
                { value: "", label: { th: "ไม่สลับ", en: "Do not switch" } },
              ]
            );
            if (!chosen) return;
            // "if 「Camellya」 is one of the switched characters" — the character
            // leaving the Leader slot is switched too, not only the one arriving
            // (906.2, and FAQ #52 on SD01-009 answers exactly this).
            if (ctx.switchLeaderTo(chosen).includes("Camellya")) { ctx.levelUpCharacter("Camellya"); }
          },
      },
    ],
  }),
  defineCard({
    type: "action",
    id: "BP01-048",
    name: "Crimson Blossom",
    character: "Camellya",
    set: "BP01",
    imageId: "BP01-048",
    altImageIds: ["BP01-048_2"],
    cost: 1,
    color: "red",
    speed: 14,
    attack: 1,
    rarity: 1,
    subtypes: ["Resonance Skill"],
    effects: [
      {
        condition: ["leader", "counter"],
        text: { th: "[Leader Skill] [Counter] Level up ให้ Camellya ของคุณ", en: "[Leader Skill] [Counter] Level up your Camellya" },
        resolve: (ctx) => ctx.levelUpCharacter("Camellya"),
      },
    ],
  }),
  defineCard({
    type: "action",
    id: "BP01-049",
    name: "Fervor Efflorescent",
    character: "Camellya",
    set: "BP01",
    imageId: "BP01-049",
    cost: 2,
    color: "red",
    speed: 13,
    attack: 5,
    rarity: 3,
    subtypes: ["Resonance Liberation"],
    effects: [],
  }),
  defineCard({
    type: "action",
    id: "BP01-050",
    name: "Crimson Pistil",
    character: "Camellya",
    set: "BP01",
    imageId: "BP01-050",
    altImageIds: ["BP01-050_2"],
    cost: 0,
    color: "red",
    speed: 6,
    attack: 1,
    rarity: 1,
    subtypes: ["Basic Attack"],
    effects: [
      {
        condition: ["combo"],
        text: {
          th: "[Combo] หากใน Action area ของเจ้าของมีการ์มากกว่าหรือเท่ากับ 2 ใบ การ์ดใบนี้ได้รับ +1 ดาเมจ",
          en: "[Combo] If your Action area has 2 or more cards, this card gains +1 damage",
        },
        resolve: (ctx) => {
            if (ctx.actionZone().length >= 2) ctx.buff({ cardId: ctx.self.id }, "attack", 1, "battle");
          },
      },
    ],
  }),
  defineCard({
    type: "action",
    id: "BP01-052",
    name: "Origin Calculus • Basic Attack",
    character: "Shorekeeper",
    set: "BP01",
    imageId: "BP01-052",
    altImageIds: ["BP01-052_2"],
    cost: 0,
    color: "red",
    speed: 5,
    attack: 1,
    rarity: 1,
    subtypes: ["Normal Attack", "Basic Attack"],
    effects: [],
  }),
  defineCard({
    type: "action",
    id: "BP01-054",
    name: "Enlightenment",
    character: "Shorekeeper",
    set: "BP01",
    imageId: "BP01-054",
    cost: 0,
    color: "red",
    speed: 0,
    attack: 0,
    rarity: 1,
    subtypes: ["Intro Skill"],
    effects: [
      {
        condition: ["combo"],
        text: {
          th: "[Combo] เปลี่ยน Leader หาก Shorekeeper เป็นตัวที่ถูกสลับ ฟื้นฟู 1 พลังชีวิต",
          en: "[Combo] Switch Leaders; if 「Shorekeeper」 is one of the switched characters, heal 1 life",
        },
        resolve: (ctx) => {
            const back = ctx.board().back;
            if (back.length === 0) return;
            const chosen = ctx.chooseOption(
              { th: "สลับ Leader ไปตัวไหน", en: "Switch your Leader to?" },
              [
                ...back.map((slot) => ({ value: slot.card.name, label: { th: slot.card.name, en: slot.card.name } })),
                { value: "", label: { th: "ไม่สลับ", en: "Do not switch" } },
              ]
            );
            if (!chosen) return;
            // "if 「Shorekeeper」 is one of the switched characters" — the character
            // leaving the Leader slot is switched too, not only the one arriving
            // (906.2, and FAQ #52 on SD01-009 answers exactly this).
            if (ctx.switchLeaderTo(chosen).includes("Shorekeeper")) { ctx.heal(1); }
          },
      },
    ],
  }),
  defineCard({
    type: "action",
    id: "BP01-055",
    name: "Origin Calculus • Heavy Attack",
    character: "Shorekeeper",
    set: "BP01",
    imageId: "BP01-055",
    altImageIds: ["BP01-055_2"],
    cost: 0,
    color: "red",
    speed: 3,
    attack: 1,
    rarity: 1,
    subtypes: ["Normal Attack", "Heavy Attack"],
    effects: [
      {
        condition: ["passive"],
        text: {
          th: "หากพลังชีวิตของเจ้าของ มากกว่าฝ่ายตรงข้าม การ์ดใบนี้ได้รับ +1 ดาเมจ",
          en: "If your life is higher than your opponent's, this card gains +1 damage",
        },
        resolve: (ctx) => {
            if (ctx.life() > ctx.life(ctx.opponentId)) {
              ctx.buff({ cardId: ctx.self.id }, "attack", 1, "turn");
            }
          },
      },
    ],
  }),
  defineCard({
    type: "action",
    id: "BP01-056",
    name: "Chaos Theory",
    character: "Shorekeeper",
    set: "BP01",
    imageId: "BP01-056",
    altImageIds: ["BP01-056_2"],
    cost: 1,
    color: "red",
    speed: 11,
    attack: 1,
    rarity: 1,
    subtypes: ["Resonance Skill"],
    effects: [
      {
        condition: ["leader", "judgement"],
        text: { th: "[Judgement] หากชนะ Level up ให้「Shorekeeper」 ของเจ้าของ", en: "[Judgement] If you win, level up your 「Shorekeeper」" },
        resolve: (ctx) => { if (ctx.wonLastBattle()) ctx.levelUpCharacter("Shorekeeper"); },
      },
    ],
  }),
  defineCard({
    type: "action",
    id: "BP01-057",
    name: "End loop",
    character: "Shorekeeper",
    set: "BP01",
    imageId: "BP01-057",
    cost: 1,
    color: "green",
    speed: 11,
    attack: 0,
    rarity: 3,
    subtypes: ["Resonance Liberation"],
    grants: {
      comboDraw: {
        condition: ["combo"],
        text: { th: "[Combo] จั่วการ์ด 1 ใบ", en: "[Combo] Draw a card." },
        resolve: (ctx) => ctx.draw(1),
      },
    },
    effects: [
      {
        // The printed trigger is [Counter] alone — the [Combo] in the text is
        // part of the ability handed out (see `grants`), not a second trigger
        // for this one.
        condition: ["leader", "counter"],
        text: {
          th: "[Counter] ในรอบนี้ การ์ด〈Intro Skill〉2 ใบถัดไปที่เล่นได้รับ \"[Combo] จั่วการ์ด 1 ใบ\"",
          en: "[Counter] This round, the next 2 〈Intro Skill〉 cards played gain \"[Combo] Draw a card.\"",
        },
        resolve: (ctx) =>
            ctx.grantEffect({ subtype: "Intro Skill" }, "comboDraw", "turn", { limit: 2 }),
      },
      {
        condition: ["leader", "judgement", "follow"],
        followCount: 8,
        text: {
          th: "[Judgement] หากชนะ ฟื้นฟู 1 พลังชีวิตและได้รับ +8 [follow-up attack]",
          en: "[Judgement] If you win, heal 1 life and gain +8 [follow-up attack]",
        },
        resolve: (ctx) => {
            if (!ctx.wonLastBattle()) return;
            ctx.heal(1);
            ctx.grantFollowUp(8);
          },
      },
    ],
  }),
  defineCard({
    type: "action",
    id: "BP01-059",
    name: "Wooly Attack • Basic Attack",
    character: "Encore",
    set: "BP01",
    imageId: "BP01-059",
    altImageIds: ["BP01-059_2"],
    cost: 0,
    color: "red",
    speed: 5,
    attack: 1,
    rarity: 1,
    subtypes: ["Normal Attack", "Basic Attack"],
    effects: [
      {
        condition: ["advantage", "counter"],
        text: {
          th: "[Advantage] [Counter] หาก Leader เป็น 「Encore」 ความเร็วของการ์ดใบนี้เป็น 10",
          en: "[Advantage] [Counter] If your Leader is 「Encore」, this card's Speed becomes 10",
        },
        resolve: (ctx) => {
            if (ctx.leaderName() === "Encore") ctx.setStat({ cardId: ctx.self.id }, "speed", 10, "battle");
          },
      },
    ],
  }),
  defineCard({
    type: "action",
    id: "BP01-060",
    name: "Wooly Attack • Heavy Attack",
    character: "Encore",
    set: "BP01",
    imageId: "BP01-060",
    altImageIds: ["BP01-060_2"],
    cost: 0,
    color: "red",
    speed: 3,
    attack: 1,
    rarity: 1,
    subtypes: ["Normal Attack", "Heavy Attack"],
    effects: [
      {
        condition: ["judgement"],
        text: {
          th: "หากสร้างความเสียหายใส่ฝ่ายตรงข้าม หาก Leader เป็น 「Encore」 จั่วการ์ด 1 ใบ",
          en: "If you deal damage to your opponent and your Leader is 「Encore」, draw 1 card",
        },
        resolve: (ctx) => {
            if (!ctx.wonLastBattle()) return;
            if (ctx.leaderName() !== "Encore") return;
            if (ctx.useLimit(1)) ctx.draw(1);
          },
      },
    ],
  }),
  defineCard({
    type: "action",
    id: "BP01-061",
    name: "Black & White Woolies",
    character: "Encore",
    set: "BP01",
    imageId: "BP01-061",
    altImageIds: ["BP01-061_2"],
    cost: 0,
    color: "red",
    speed: 0,
    attack: 3,
    rarity: 1,
    subtypes: ["Forte Circuit", "Resonance Liberation"],
    effects: [
      {
        condition: ["leader", "counter", "combo"],
        text: { th: "[Counter] / [Combo] ในรอบนี้ เจ้าของจะไม่สามารถโจมตีต่อเนื่องได้", en: "[Counter] / [Combo] This round, you cannot Combo" },
        resolve: (ctx) => ctx.restrict("noCombo"),
      },
    ],
  }),
  defineCard({
    type: "action",
    id: "BP01-062",
    name: "Cosmos Rave",
    character: "Encore",
    set: "BP01",
    imageId: "BP01-062",
    cost: 2,
    color: "red",
    speed: 11,
    attack: 3,
    rarity: 3,
    subtypes: ["Resonance Liberation"],
    effects: [
      {
        condition: ["passive", "advantage"],
        text: { th: "[Advantage] คอสของการ์ดใบนี้ -1", en: "[Advantage] This card's cost -1" },
        resolve: (ctx) => ctx.buff({ cardId: ctx.self.id }, "cost", -1, "turn"),
      },
      {
        condition: ["counter"],
        text: {
          th: "[Counter] นำการ์ด 「Encore」 Level 2 วางบนสุดของ 「Encore」 ของเจ้าของ (นับเป็นการ Level up)  สลับ Leader เป็น 「Encore」",
          en: "[Counter] Put an 「Encore」 Level 2 card on top of your 「Encore」 (this counts as leveling up), then switch your Leader to 「Encore」",
        },
        resolve: (ctx) => {
            // "Level 2" is printed on the card, so nothing else is on offer —
            // and this is the one way an 「Encore」 Level 2 reaches the field
            // without climbing to it.
            ctx.levelUpCharacter("Encore", { level: 2 });
            ctx.switchLeaderTo("Encore");
          },
      },
    ],
  }),
  defineCard({
    type: "action",
    id: "BP01-063",
    name: "Woolies Helpers",
    character: "Encore",
    set: "BP01",
    imageId: "BP01-063",
    altImageIds: ["BP01-063_2"],
    cost: 0,
    color: "red",
    speed: 0,
    attack: 0,
    rarity: 1,
    subtypes: ["Intro Skill"],
    effects: [
      {
        condition: ["combo"],
        text: {
          th: "[Combo] เปลี่ยน Leader หาก Encore เป็นตัวที่ถูกสลับ นำการ์ดสีแดงของ Encore ที่ไม่ใช่ 〈Intro Skill〉 1 ใบขึ้นมือ",
          en: "[Combo] Switch Leaders; if 「Encore」 is one of the switched characters, take 1 of Encore's red cards that isn't 〈Intro Skill〉 to hand",
        },
        resolve: (ctx) => {
            const back = ctx.board().back;
            if (back.length === 0) return;
            const chosen = ctx.chooseOption(
              { th: "สลับ Leader ไปตัวไหน", en: "Switch your Leader to?" },
              [
                ...back.map((slot) => ({ value: slot.card.name, label: { th: slot.card.name, en: slot.card.name } })),
                { value: "", label: { th: "ไม่สลับ", en: "Do not switch" } },
              ]
            );
            if (!chosen) return;
            // "if 「Encore」 is one of the switched characters" — the character
            // leaving the Leader slot is switched too, not only the one arriving
            // (906.2, and FAQ #52 on SD01-009 answers exactly this).
            if (ctx.switchLeaderTo(chosen).includes("Encore")) { ctx.searchDeck({ character: "Encore", color: "red" }, 1); }
          },
      },
    ],
  }),
  defineCard({
    type: "action",
    id: "BP01-064",
    name: "Wooly Attack • Dodge Counter",
    character: "Encore",
    set: "BP01",
    imageId: "BP01-064",
    altImageIds: ["BP01-064_2"],
    cost: 0,
    color: "blue",
    speed: null,
    attack: 3,
    rarity: 1,
    subtypes: ["Dodge Counter"],
    effects: [],
  }),
  defineCard({
    type: "action",
    id: "BP01-065",
    name: "Vibration Manifestation • Heavy Attack",
    character: "Rover (F)",
    set: "BP01",
    imageId: "BP01-065",
    altImageIds: ["BP01-065_2"],
    cost: 0,
    color: "red",
    speed: 6,
    attack: 1,
    rarity: 1,
    subtypes: ["Normal Attack", "Heavy Attack"],
    effects: [
      {
        condition: ["combo"],
        text: {
          th: "[Combo] สามารถทิ้งการ์ด 1 ใบ หากทำการ์ดใบนี้ได้รับ +1 ดาเมจ",
          en: "[Combo] You may discard 1 card; if you do, this card gains +1 damage",
        },
        resolve: (ctx) => {
            const pick = ctx.chooseCard(
              { th: "ทิ้งการ์ด 1 ใบเพื่อ +1 ดาเมจ", en: "Discard a card for +1 damage?" },
              ctx.hand(),
              { optional: true }
            );
            if (!pick) return;
            ctx.discardCards([pick]);
            ctx.buff({ cardId: ctx.self.id }, "attack", 1, "battle");
          },
      },
    ],
  }),
  defineCard({
    type: "action",
    id: "BP01-067",
    name: "Vibration Manifestation • Heavy Attack",
    character: "Rover (M)",
    set: "BP01",
    imageId: "BP01-067",
    altImageIds: ["BP01-067_2"],
    cost: 0,
    color: "red",
    speed: 6,
    attack: 1,
    rarity: 1,
    subtypes: ["Normal Attack", "Heavy Attack"],
    effects: [
      {
        condition: ["combo"],
        text: {
          th: "[Combo] สามารถทิ้งการ์ด 1 ใบ หากทำการ์ดใบนี้ได้รับ +1 ดาเมจ",
          en: "[Combo] You may discard 1 card; if you do, this card gains +1 damage",
        },
        resolve: (ctx) => {
            const pick = ctx.chooseCard(
              { th: "ทิ้งการ์ด 1 ใบเพื่อ +1 ดาเมจ", en: "Discard a card for +1 damage?" },
              ctx.hand(),
              { optional: true }
            );
            if (!pick) return;
            ctx.discardCards([pick]);
            ctx.buff({ cardId: ctx.self.id }, "attack", 1, "battle");
          },
      },
    ],
  }),
  defineCard({
    type: "action",
    id: "BP01-069",
    name: "Feather Release • Dodge",
    character: "Yangyang",
    set: "BP01",
    imageId: "BP01-069",
    altImageIds: ["BP01-069_2"],
    cost: 0,
    color: "blue",
    speed: null,
    attack: 0,
    rarity: 1,
    subtypes: ["Dodge", "Airborn"],
    effects: [
      {
        condition: ["judgement", "follow"],
        followCount: 1,
        text: { th: "[Judgement] หากชนะ ได้รับ +1[follow-up attack]", en: "[Judgement] If you win, gain +1 [follow-up attack]" },
        resolve: (ctx) => { if (ctx.wonLastBattle()) ctx.grantFollowUp(1); },
      },
      {
        condition: ["counterPhaseEnd"],
        text: {
          th: "[At end of each counter phase] หาก Leader เป็น Yangyang สามารถจ่าย 1 cost จากนั้นนั้นการ์ดใบนี้ขึ้นมือ",
          en: "[At end of each counter phase] If your Leader is Yangyang, you may pay 1 cost to return this card to hand",
        },
        resolve: (ctx) => {
            if (ctx.leaderName() !== "Yangyang") return;
            if (!ctx.confirm({ th: "จ่าย 1 cost เพื่อเอาการ์ดใบนี้กลับขึ้นมือไหม", en: "Pay 1 to return this card to hand?" })) return;
            if (ctx.spendCost(1)) ctx.returnToHand();
          },
      },
    ],
  }),
  defineCard({
    type: "action",
    id: "BP01-070",
    name: "Zephyr Domain",
    character: "Yangyang",
    set: "BP01",
    imageId: "BP01-070",
    altImageIds: ["BP01-070_2"],
    cost: 1,
    color: "red",
    speed: 14,
    attack: 2,
    rarity: 1,
    subtypes: ["Resonance Skill"],
    effects: [
      {
        condition: ["leader", "judgement"],
        text: {
          th: "[Leader Skill] [Judgement] หากชนะ นำการ์ดสีฟ้า 1 ใบ จากกองทิ้งขึ้นมือ",
          en: "[Leader Skill] [Judgement] If you win, take 1 blue card from the trash to hand",
        },
        resolve: (ctx) => {
          if (ctx.wonLastBattle()) ctx.trashToHand(1, { color: "blue" });
        },
      },
    ],
  }),
  defineCard({
    type: "action",
    id: "BP01-071",
    name: "Echoing Feathers",
    character: "Yangyang",
    set: "BP01",
    imageId: "BP01-071",
    altImageIds: ["BP01-071_2"],
    cost: 0,
    color: "red",
    speed: 6,
    attack: 1,
    rarity: 1,
    subtypes: ["Mid-air Attack"],
    effects: [
      {
        condition: ["combo"],
        text: {
          th: "[Combo] ในรอบนี้ หากเจ้าของเล่นการ์ด 〈Airborn〉นำการ์ด 1 ใบบนสุดของเด็ควางที่ Concerto Area",
          en: "[Combo] This round, if you played an 〈Airborn〉 card, put the top card of your deck into the Concerto Area",
        },
        resolve: (ctx) => {
          if (ctx.countPlayedThisTurn({ subtype: "Airborn" }) > 0) ctx.topToConcerto(1);
        },
      },
    ],
  }),
  defineCard({
    type: "action",
    id: "BP01-072",
    name: "DAKA DAKA!",
    character: "Chixia",
    set: "BP01",
    imageId: "BP01-072",
    altImageIds: ["BP01-072_2"],
    cost: 1,
    color: "red",
    speed: 12,
    attack: 2,
    rarity: 1,
    subtypes: ["Forte Circuit"],
    effects: [
      {
        condition: ["leader", "advantage", "counter"],
        text: {
          th: "[Leader Skill] [Advantage] [Counter] นำการ์ด {Basic Attack} หรือ {Resonance Liberation} 1 ใบจากกองทิ้งขึ้นมือ",
          en: "[Leader Skill] [Advantage] [Counter] Take 1 {Basic Attack} or {Resonance Liberation} card from the trash to hand",
        },
        resolve: (ctx) => {
            const options = ctx.board().trash.filter(
              (c) => ctx.countMatching([c], { subtype: ["Basic Attack", "Resonance Liberation"] }) > 0
            );
            const pick = ctx.chooseCard(
              { th: "นำการ์ดจากกองทิ้งขึ้นมือ", en: "Take a card from the trash?" },
              options,
              { optional: true }
            );
            if (pick) ctx.trashToHand(1, { cardId: pick.id });
          },
      },
    ],
  }),
  defineCard({
    type: "action",
    id: "BP01-073",
    name: "Overflowing Radiance",
    character: "Jinshi",
    set: "BP01",
    imageId: "BP01-073",
    altImageIds: ["BP01-073_2"],
    cost: 1,
    color: "red",
    speed: 13,
    attack: 1,
    rarity: 1,
    subtypes: ["Resonance Skill"],
    effects: [
      {
        condition: ["leader", "judgement"],
        text: { th: "[Judgement] หากชนะ นำ 「Incarnation」 ขึ้นมือ จากนั้นสับเด็ค", en: "[Judgement] If you win, take 「Incarnation」 to hand, then shuffle your deck" },
        resolve: (ctx) => {
            if (!ctx.wonLastBattle()) return;
            // "Incarnation" is the name of SD02-010.
            ctx.searchDeck({ cardId: "SD02-010" }, 1);
          },
      },
    ],
  }),
  defineCard({
    type: "action",
    id: "BP01-074",
    name: "Illuminous Epiphany",
    character: "Jinshi",
    set: "BP01",
    imageId: "BP01-074",
    altImageIds: ["Bp01-074_2"],
    cost: 1,
    color: "red",
    speed: 11,
    attack: 0,
    rarity: 1,
    subtypes: ["Forte Circuit", "Resonance Skill"],
    effects: [
      {
        condition: ["leader", "combo"],
        text: {
          th: "[Combo] การ์ดใบนี้ได้รับ +1 ดาเมจ ตามจำนวนการ์ดที่อยู่บน Action area ฝ่ายเรา",
          en: "[Combo] This card gains +1 damage for each card in your Action area",
        },
        resolve: (ctx) => {
            const stacked = ctx.actionZone().length;
            if (stacked > 0) ctx.buff({ cardId: ctx.self.id }, "attack", stacked, "battle");
          },
      },
      {
        condition: ["leader", "counter", "combo"],
        text: { th: "[Counter] / [Combo] ในรอบนี้ เจ้าของไม่สามารถโจมตีต่อเนื่องได้", en: "[Counter] / [Combo] This round, you cannot Combo" },
        resolve: (ctx) => ctx.restrict("noCombo"),
      },
    ],
  }),
  defineCard({
    type: "action",
    id: "BP01-077",
    name: "Ice Burst",
    character: "Sanhua",
    set: "BP01",
    imageId: "BP01-077",
    altImageIds: ["BP01-077_2"],
    cost: 1,
    color: "red",
    speed: 11,
    attack: 2,
    rarity: 1,
    subtypes: ["Forte Circuit", "Resonance Skill"],
    effects: [
      {
        condition: ["leader", "judgement"],
        text: {
          th: "[Judgement] หากชนะและมีการ์ดของ 【Sanhua】 ใน Concerto Area เจ้าของสามารถสลับ Leader ได้",
          en: "[Judgement] If you win and have a 【Sanhua】 card in your Concerto Area, you may switch Leaders",
        },
        resolve: (ctx) => {
            if (!ctx.wonLastBattle()) return;
            if (ctx.countMatching(ctx.concerto(), { character: "Sanhua" }) === 0) return;
            const back = ctx.board().back;
            if (back.length === 0) return;
            const chosen = ctx.chooseOption(
              { th: "สลับ Leader ไปตัวไหน", en: "Switch your Leader to?" },
              [
                ...back.map((slot) => ({ value: slot.card.name, label: { th: slot.card.name, en: slot.card.name } })),
                { value: "", label: { th: "ไม่สลับ", en: "Do not switch" } },
              ]
            );
            if (chosen) ctx.switchLeaderTo(chosen);
          },
      },
    ],
  }),
];
