// SD01 — one entry per printed card number.
//
// Each card carries what is printed on it AND what it does. See
// src/cardDef.ts for the shape, and _EXAMPLE.ts for a filled-in card.
//
// Generated by `npm run sync:cards`; new card numbers are appended and
// anything already here is left untouched. Fill these in by hand.
import { defineCard } from "../cardDef";
import type { CardDef } from "../cardDef";

export const SD01: CardDef[] = [
  defineCard({
    type: "action",
    id: "SD01-023",
    name: "Echoing Orchestra",
    character: "Rover (F)",
    set: "SD01",
    imageId: "SD01-023",
    altImageIds: ["SD01-023_3"],
    cost: 3,
    color: "red",
    speed: 14,
    attack: 5,
    rarity: 1,
    subtypes: ["Resonance Liberation"],
    effects: [
      {
        condition: ["leader", "judgement"],
        text: { th: "[Leader Skill] [Judgement] หากชนะ ฟื้นฟู 5 พลังชีวิต" },
        resolve: (ctx) => {
          if (ctx.wonLastBattle()) ctx.heal(5);
        },
      },
    ],
  }),
  defineCard({
    type: "leader",
    id: "BP01-018",
    name: "Rover (F)",
    character: "Rover (F)",
    set: "SD01",
    imageId: "BP01-018",
    altImageIds: ["BP01-018_2"],
    level: 0,
    rarity: 1,
    weapon: "sword",
    element: "spectro",
    effects: [
      {
        condition: ["leader", "counter"],
        text: {
          th: "[Leader] [Counter] หาก counter ด้วยการ์ดสีเขียว สามารถแสดงการ์ด 2 ใบบนสุดของเด็คจากนั้นนำขึ้นมือ",
          en: "[Leader] [Counter] If you counter with green card, reaveal up to 2 card from top of your deck and draw them to hands",
        },
        resolve: (ctx) => {
          if (!(ctx.lastPlayedColor() === "green")) return;
          const revealed = ctx.revealTop(2);
          if (revealed.length === 0) return;
          if (
            ctx.confirm({
              th: "แสดงการ์ด 2 ใบบนสุดของเด็ค นำขึ้นมือไหม",
              en: "Reveal 2 from the top of your deck and take them?",
            })
          ) {
            ctx.deckToHand(2);
          }
        },
      },
    ],
  }),
  defineCard({
    type: "leader",
    id: "BP01-024",
    name: "Yangyang",
    character: "Yangyang",
    set: "SD01",
    imageId: "BP01-024",
    altImageIds: ["BP01-024_2", "BP01-024_PR"],
    level: 0,
    rarity: 1,
    weapon: "sword",
    element: "aero",
    effects: [
      {
        condition: ["leader", "counter"],
        text: { th: "[Leader] [Counter] หาก counter ด้วยการ์ดสีฟ้า สามารถนำการ์ด 1 ใบบนสุดของเด็ควางที่ Concerto area" },
        resolve: (ctx) => {
          if (!(ctx.lastPlayedColor() === "blue")) return;
          if (ctx.board().actionDeck.length === 0) return;
          if (
            ctx.confirm({
              th: "นำการ์ด 1 ใบบนสุดของเด็ควางที่ Concerto Area ไหม",
              en: "Put 1 from the top of your deck into the Concerto area?",
            })
          ) {
            ctx.topToConcerto(1);
          }
        },
      },
    ],
  }),
  defineCard({
    type: "leader",
    id: "BP01-027",
    name: "Chixia",
    character: "Chixia",
    set: "SD01",
    imageId: "BP01-027",
    altImageIds: ["BP01-027_2", "BP01-027_2PR"],
    level: 0,
    rarity: 1,
    weapon: "pistols",
    element: "fusion",
    effects: [
      {
        condition: ["leader", "counter"],
        text: { th: "[Leader] [Counter] หาก counter ด้วยการ์ดสีแดง ทำ 1 ดาเมจใส่ฝ่ายตรงข้าม" },
        resolve: (ctx) => { if (ctx.lastPlayedColor() === "red") ctx.damage(1); },
      },
    ],
  }),
  defineCard({
    type: "leader",
    id: "SD01-001",
    name: "Rover (F)",
    character: "Rover (F)",
    set: "SD01",
    imageId: "SD01-001",
    level: 2,
    rarity: 3,
    weapon: "sword",
    element: "spectro",
    effects: [
      {
        condition: ["turnStart"],
        text: {
          th: "[At start of own turn] จั่วการ์ด 1 ใบ",
          en: "[At start of own turn] Draw 1 card",
        },
        resolve: (ctx) => ctx.draw(1),
      },
    ],
  }),
  defineCard({
    type: "leader",
    id: "SD01-002",
    name: "Rover (F)",
    character: "Rover (F)",
    set: "SD01",
    imageId: "SD01-002",
    level: 1,
    rarity: 1,
    weapon: "sword",
    element: "spectro",
    effects: [
      {
        condition: ["leader", "judgement"],
        text: {
          th: "[Leader] [Judgement]หากแพ้ให้กับการ์ดสีแดงในการเล่นการ์ดสีเขียว สามารถแสดงการ์ด 1 ใบบนสุดของเด็ค จากนั้นนำขึ้นมือ",
          en: "[Leader] [Judgement] If you lose to a red card while playing a green card, you may reveal the top card of your deck and add it to your hand",
        },
        resolve: (ctx) => {
          if (!(ctx.lostTo("red") && ctx.lastPlayedColor() === "green")) return;
          const revealed = ctx.revealTop(1);
          if (revealed.length === 0) return;
          if (
            ctx.confirm({
              th: "แสดงการ์ด 1 ใบบนสุดของเด็ค นำขึ้นมือไหม",
              en: "Reveal 1 from the top of your deck and take it?",
            })
          ) {
            ctx.deckToHand(1);
          }
        },
      },
    ],
  }),
  defineCard({
    type: "leader",
    id: "SD01-003",
    name: "Yangyang",
    character: "Yangyang",
    set: "SD01",
    imageId: "SD01-003",
    altImageIds: ["SD01-003_4"],
    level: 2,
    rarity: 3,
    weapon: "sword",
    element: "aero",
    effects: [
      {
        condition: ["leader", "counter"],
        text: { th: "[Leader] [Counter] หากฝ่ายตรงข้าม counter ด้วยการ์ดสีแดง ฝ่ายตรงข้ามต้องจ่าย cost เพิ่ม 1 ใบ หากไม่ทำ ฝ่ายตรงข้ามได้รับ 3 ดาเมจ" },
        resolve: (ctx) => {
            if (ctx.lastPlayedColor(ctx.opponentId) !== "red") return;
            const paid =
              ctx.confirm(
                { th: "จ่าย 1 cost ไหม ถ้าไม่จ่ายจะได้รับ 3 ดาเมจ", en: "Pay 1 cost? Refusing costs you 3 damage." },
                ctx.opponentId
              ) && ctx.spendCost(1, ctx.opponentId);
            if (!paid) ctx.damage(3, ctx.opponentId);
          },
      },
    ],
  }),
  defineCard({
    type: "leader",
    id: "SD01-004",
    name: "Yangyang",
    character: "Yangyang",
    set: "SD01",
    imageId: "SD01-004",
    level: 1,
    rarity: 1,
    weapon: "sword",
    element: "aero",
    effects: [
      {
        condition: ["leader", "judgement"],
        text: { th: "[Leader] [Judgement] หากแพ้ให้การ์ดสีเขียวในการเล่นการ์ดสีฟ้า สามารถแสดงการ์ด 1 ใบบนสุดของเด็ค จากนั้นนำขึ้นมือ" },
        resolve: (ctx) => {
          if (!(ctx.lostTo("green") && ctx.lastPlayedColor() === "blue")) return;
          const revealed = ctx.revealTop(1);
          if (revealed.length === 0) return;
          if (ctx.confirm({
            th: "แสดงการ์ด 1 ใบบนสุดของเด็ค นำขึ้นมือไหม",
            en: "Reveal 1 from the top of your deck and take it?",
          })) ctx.deckToHand(1);
        },
      },
    ],
  }),
  defineCard({
    type: "leader",
    id: "SD01-005",
    name: "Chixia",
    character: "Chixia",
    set: "SD01",
    imageId: "SD01-005",
    altImageIds: ["SD01-005_4"],
    level: 2,
    rarity: 3,
    weapon: "pistols",
    element: "fusion",
    effects: [
      {
        condition: ["leader"],
        text: { th: "การ์ด [Leader skill] ของ Chixia ได้รับ +3 ดาเมจ" },
        resolve: (ctx) => ctx.buff({ character: "Chixia", keyword: "leader" }, "attack", 3, "whileActive"),
      },
    ],
  }),
  defineCard({
    type: "leader",
    id: "SD01-006",
    name: "Chixia",
    character: "Chixia",
    set: "SD01",
    imageId: "SD01-006",
    level: 1,
    rarity: 1,
    weapon: "pistols",
    element: "fusion",
    effects: [
      {
        condition: ["leader", "judgement"],
        text: { th: "[Leader] [Judgement] หากแพ้การ์ดสีฟ้าในการเล่นการ์ดสีแดง สามารถแสดงการ์ด 1 ใบบนสุดของเด็ค จากนั้นนำขึ้นมือ" },
        resolve: (ctx) => {
          if (!(ctx.lostTo("blue") && ctx.lastPlayedColor() === "red")) return;
          const revealed = ctx.revealTop(1);
          if (revealed.length === 0) return;
          if (ctx.confirm({
            th: "แสดงการ์ด 1 ใบบนสุดของเด็ค นำขึ้นมือไหม",
            en: "Reveal 1 from the top of your deck and take it?",
          })) ctx.deckToHand(1);
        },
      },
    ],
  }),
  defineCard({
    type: "action",
    id: "SD01-007",
    name: "POW POW • Basic Attack",
    character: "Chixia",
    set: "SD01",
    imageId: "SD01-007",
    cost: 0,
    color: "red",
    speed: 6,
    attack: 1,
    rarity: 1,
    subtypes: ["Normal Attack", "Basic Attack"],
    effects: [],
  }),
  defineCard({
    type: "action",
    id: "SD01-008",
    name: "POW POW • Dodge Counter",
    character: "Chixia",
    set: "SD01",
    imageId: "SD01-008",
    cost: 0,
    color: "blue",
    speed: null,
    attack: 3,
    rarity: 1,
    subtypes: ["Dodge Counter"],
    effects: [],
  }),
  defineCard({
    type: "action",
    id: "SD01-009",
    name: "Leaping Flames",
    character: "Chixia",
    set: "SD01",
    imageId: "SD01-009",
    cost: 0,
    color: "red",
    speed: 0,
    attack: 0,
    rarity: 1,
    subtypes: ["Intro Skill"],
    effects: [
      {
        condition: ["combo"],
        text: { th: "[Combo] เปลี่ยน Leader หากเปลี่ยนเป็น Chixia การ์ดใบนี้ได้รับ +2 ดาเมจ" },
        resolve: (ctx) => {
            const back = ctx.board().back;
            if (back.length === 0) return;
            const chosen = ctx.chooseOption(
              { th: "สลับ Leader ไปตัวไหน", en: "Switch your Leader to?" },
              [
                ...back.map((slot) => ({ value: slot.card.name, label: { th: slot.card.name, en: slot.card.name } })),
                { value: "", label: { th: "ไม่สลับ", en: "Do not switch" } },
              ]
            );
            if (!chosen) return;
            ctx.switchLeaderTo(chosen);
            if (chosen === "Chixia") { ctx.buff({ cardId: ctx.self.id }, "attack", 2, "battle"); }
          },
      },
    ],
  }),
  defineCard({
    type: "action",
    id: "SD01-010",
    name: "Whizzing Fight Spirit",
    character: "Chixia",
    set: "SD01",
    imageId: "SD01-010",
    cost: 1,
    color: "red",
    speed: 8,
    attack: 2,
    rarity: 1,
    subtypes: ["Resonance Skill"],
    effects: [
      {
        condition: ["leader", "judgement"],
        text: { th: "[Leader Skill] [Judgement] หากแพ้การ์ดสีฟ้าในการเล่นการ์ดใบนี้ นำการ์ดใบนี้กลับขึ้นมือ" },
        resolve: (ctx) => { if (ctx.lostTo("blue")) ctx.returnToHand(); },
      },
    ],
  }),
  defineCard({
    type: "action",
    id: "SD01-011",
    name: "Blazing Flames",
    character: "Chixia",
    set: "SD01",
    imageId: "SD01-011",
    altImageIds: ["SD01-011_3"],
    cost: 3,
    color: "red",
    speed: 12,
    attack: 7,
    rarity: 1,
    subtypes: ["Resonance Liberation"],
    effects: [],
  }),
  defineCard({
    type: "action",
    id: "SD01-012",
    name: "Feather as Blade • Basic Attack",
    character: "Yangyang",
    set: "SD01",
    imageId: "SD01-012",
    cost: 0,
    color: "red",
    speed: 8,
    attack: 1,
    rarity: 1,
    subtypes: ["Normal Attack", "Basic Attack"],
    effects: [],
  }),
  defineCard({
    type: "action",
    id: "SD01-013",
    name: "Feather as Blade • Dodge",
    character: "Yangyang",
    set: "SD01",
    imageId: "SD01-013",
    cost: 0,
    color: "blue",
    speed: null,
    attack: 0,
    rarity: 1,
    subtypes: ["Dodge"],
    effects: [
      {
        condition: ["judgement", "follow"],
        followCount: 2,
        text: { th: "[Judgement] หากชนะ ได้รับ +2[follow-up attack]" },
        resolve: (ctx) => { if (ctx.wonLastBattle()) ctx.grantFollowUp(2); },
      },
    ],
  }),
  defineCard({
    type: "action",
    id: "SD01-014",
    name: "Whispering Breeze",
    character: "Yangyang",
    set: "SD01",
    imageId: "SD01-014",
    cost: 0,
    color: "red",
    speed: 0,
    attack: 0,
    rarity: 1,
    subtypes: ["Intro Skill"],
    effects: [
      {
        condition: ["combo"],
        text: { th: "[Combo] เปลี่ยน Leader หากเปลี่ยนเป็น Yangyang นำการ์ด 1 ใบบนสุดของเด็ควางที่ Concerto area" },
        resolve: (ctx) => {
            const back = ctx.board().back;
            if (back.length === 0) return;
            const chosen = ctx.chooseOption(
              { th: "สลับ Leader ไปตัวไหน", en: "Switch your Leader to?" },
              [
                ...back.map((slot) => ({ value: slot.card.name, label: { th: slot.card.name, en: slot.card.name } })),
                { value: "", label: { th: "ไม่สลับ", en: "Do not switch" } },
              ]
            );
            if (!chosen) return;
            ctx.switchLeaderTo(chosen);
            if (chosen === "Yangyang") { ctx.topToConcerto(1); }
          },
      },
    ],
  }),
  defineCard({
    type: "action",
    id: "SD01-015",
    name: "Jump",
    character: "Yangyang",
    set: "SD01",
    imageId: "SD01-015",
    cost: 0,
    color: "green",
    speed: 7,
    attack: 0,
    rarity: 1,
    subtypes: ["Movement", "Airborn"],
    effects: [
      {
        condition: ["judgement", "follow"],
        followCount: 1,
        text: { th: "[Judgement] หากชนะ จั่วการ์ด 1 ใบ และได้รับ +1[follow-up attack]" },
        resolve: (ctx) => {
            if (!ctx.wonLastBattle()) return;
            ctx.draw(1);
            ctx.grantFollowUp(1);
          },
      },
    ],
  }),
  defineCard({
    type: "action",
    id: "SD01-016",
    name: "Wind Spirals",
    character: "Yangyang",
    set: "SD01",
    imageId: "SD01-016",
    altImageIds: ["SD01-016_3"],
    cost: 0,
    color: "red",
    speed: 13,
    attack: 4,
    rarity: 1,
    subtypes: ["Resonance Liberation"],
    effects: [
      {
        condition: ["leader", "judgement"],
        text: { th: "[Leader Skill] [Judgement] หากชนะ ในรอบการเล่นถัดไป การ์ดสีแดงของฝ่ายตรงข้าม Cost +1" },
        resolve: (ctx) => {
            if (!ctx.wonLastBattle()) return;
            ctx.buff({ color: "red", side: "opponent" }, "cost", 1, "nextTurn");
          },
      },
    ],
  }),
  defineCard({
    type: "action",
    id: "SD01-017",
    name: "Vibration Manifestation • Basic Attack",
    character: "Rover (F)",
    set: "SD01",
    imageId: "SD01-017",
    cost: 0,
    color: "red",
    speed: 8,
    attack: 1,
    rarity: 1,
    subtypes: ["Normal Attack", "Basic Attack"],
    effects: [],
  }),
  defineCard({
    type: "action",
    id: "SD01-018",
    name: "Vibration Manifestation • Dodge",
    character: "Rover (F)",
    set: "SD01",
    imageId: "SD01-018",
    cost: 0,
    color: "blue",
    speed: null,
    attack: 0,
    rarity: 1,
    subtypes: ["Dodge"],
    effects: [
      {
        condition: ["judgement"],
        text: { th: "[Judgement] หากชนะ จั่วการ์ด 1 ใบ จากนั้นทิ้งการ์ดในมือ 1 ใบ" },
        resolve: (ctx) => {
            if (!ctx.wonLastBattle()) return;
            ctx.draw(1);
            const pick = ctx.chooseCard({ th: "เลือกการ์ดที่จะทิ้ง", en: "Discard which card?" }, ctx.hand());
            if (pick) ctx.discardCards([pick]);
          },
      },
    ],
  }),
  defineCard({
    type: "action",
    id: "SD01-019",
    name: "Waveshock",
    character: "Rover (F)",
    set: "SD01",
    imageId: "SD01-019",
    cost: 0,
    color: "red",
    speed: 0,
    attack: 0,
    rarity: 1,
    subtypes: ["Intro Skill"],
    effects: [
      {
        condition: ["combo"],
        text: { th: "[Combo] เปลี่ยน Leader หากเปลี่ยนเป็น Rover (F) จั่วการ์ด 1 ใบ" },
        resolve: (ctx) => {
            const back = ctx.board().back;
            if (back.length === 0) return;
            const chosen = ctx.chooseOption(
              { th: "สลับ Leader ไปตัวไหน", en: "Switch your Leader to?" },
              [
                ...back.map((slot) => ({ value: slot.card.name, label: { th: slot.card.name, en: slot.card.name } })),
                { value: "", label: { th: "ไม่สลับ", en: "Do not switch" } },
              ]
            );
            if (!chosen) return;
            ctx.switchLeaderTo(chosen);
            if (chosen === "Rover (F)") { ctx.draw(1); }
          },
      },
    ],
  }),
  defineCard({
    type: "action",
    id: "SD01-020",
    name: "Sensor",
    character: "Rover (F)",
    set: "SD01",
    imageId: "SD01-020",
    cost: 0,
    color: "green",
    speed: 5,
    attack: 0,
    rarity: 1,
    subtypes: ["Utilities"],
    effects: [
      {
        condition: ["judgement"],
        text: { th: "[Judgement] หากชนะ จั่วการ์ด 1 ใบ ฝ่ายตรงข้ามแสดงการ์ดในมือ" },
        resolve: (ctx) => {
            if (!ctx.wonLastBattle()) return;
            ctx.draw(1);
            ctx.revealHand(ctx.opponentId);
          },
      },
    ],
  }),
  defineCard({
    type: "action",
    id: "SD01-021",
    name: "Grapple",
    character: "Rover (F)",
    set: "SD01",
    imageId: "SD01-021",
    cost: 1,
    color: "green",
    speed: 8,
    attack: 0,
    rarity: 1,
    subtypes: ["Utilities", "Airborn"],
    effects: [
      {
        condition: ["judgement", "follow"],
        followCount: 2,
        text: { th: "[Judgement] หากชนะ จั่วการ์ด 1 ใบ ได้รับ +2[follow-up attack]" },
        resolve: (ctx) => {
            if (!ctx.wonLastBattle()) return;
            ctx.draw(1);
            ctx.grantFollowUp(2);
          },
      },
    ],
  }),
  defineCard({
    type: "action",
    id: "SD01-022",
    name: "Resonating Slashes",
    character: "Rover (F)",
    set: "SD01",
    imageId: "SD01-022",
    cost: 1,
    color: "red",
    speed: 16,
    attack: 1,
    rarity: 1,
    subtypes: ["Resonance Skill"],
    effects: [],
  }),
];
