// SD02 — one entry per printed card number.
//
// Each card carries what is printed on it AND what it does. See
// src/cardDef.ts for the shape, and _EXAMPLE.ts for a filled-in card.
//
// Generated by `npm run sync:cards`; new card numbers are appended and
// anything already here is left untouched. Fill these in by hand.
import { defineCard } from "../cardDef";
import type { CardDef } from "../cardDef";

export const SD02: CardDef[] = [
  defineCard({
    type: "leader",
    id: "BP01-021",
    name: "Rover (M)",
    character: "Rover (M)",
    set: "SD02",
    imageId: "BP01-021",
    altImageIds: ["BP01-021_2"],
    level: 0,
    rarity: 1,
    weapon: "sword",
    element: "spectro",
    effects: [
      {
        condition: ["leader", "counter"],
        text: {
          th: "[Leader] [Counter] หาก counter ด้วยการ์ดสีเขียว สามารถแสดงการ์ด 2 ใบบนสุดของเด็ค จากนั้นนำขึ้นมือ",
          en: "[Leader] [Counter] If you counter with a green card, you may reveal the top 2 cards of your deck, then take them to hand",
        },
        resolve: (ctx) => {
          if (!(ctx.lastPlayedColor() === "green")) return;
          const revealed = ctx.revealTop(2);
          if (revealed.length === 0) return;
          if (ctx.confirm({
            th: "แสดงการ์ด 2 ใบบนสุดของเด็ค นำขึ้นมือไหม",
            en: "Reveal 2 from the top of your deck and take them?",
          })) ctx.deckToHand(2);
        },
      },
    ],
  }),
  defineCard({
    type: "leader",
    id: "BP01-030",
    name: "Jinshi",
    character: "Jinshi",
    set: "SD02",
    imageId: "BP01-030",
    altImageIds: ["BP01-030_2", "BP01-030_2PR"],
    level: 0,
    rarity: 1,
    weapon: "broadblade",
    element: "spectro",
    effects: [
      {
        condition: ["leader", "counter"],
        text: { th: "[Leader] [Counter] หาก counter ด้วยการ์ดสีแดง ทำ 1 ดาเมจใส่ฝ่ายตรงข้าม", en: "[Leader] [Counter] If you counter with a red card, deal 1 damage to your opponent" },
        resolve: (ctx) => { if (ctx.lastPlayedColor() === "red") ctx.damage(1); },
      },
    ],
  }),
  defineCard({
    type: "leader",
    id: "BP01-033",
    name: "Sanhua",
    character: "Sanhua",
    set: "SD02",
    imageId: "BP01-033",
    altImageIds: ["BP01-033_2", "BP01-033_2PR"],
    level: 0,
    rarity: 1,
    weapon: "sword",
    element: "glacio",
    effects: [
      {
        condition: ["leader", "counter"],
        text: {
          th: "[Leader] [Counter] หาก counter ด้วยการ์ดสีฟ้า สามารถนำการ์ด 1 ใบบนสุดของเด็ควางที่ Concerto area",
          en: "[Leader] [Counter] If you counter with a blue card, you may put the top card of your deck into the Concerto area",
        },
        resolve: (ctx) => {
          if (!(ctx.lastPlayedColor() === "blue")) return;
          if (ctx.board().actionDeck.length === 0) return;
          if (
            ctx.confirm({
              th: "นำการ์ด 1 ใบบนสุดของเด็ควางที่ Concerto Area ไหม",
              en: "Put 1 from the top of your deck into the Concerto area?",
            })
          ) {
            ctx.topToConcerto(1);
          }
        },
      },
    ],
  }),
  defineCard({
    type: "leader",
    id: "SD02-001",
    name: "Rover (M)",
    character: "Rover (M)",
    set: "SD02",
    imageId: "SD02-001",
    level: 2,
    rarity: 3,
    weapon: "sword",
    element: "spectro",
    effects: [
      {
        condition: ["leader", "endTurn"],
        text: { th: "[Leader] [At end of each turn] จั่วการ์ด 1 ใบ", en: "[Leader] [At end of each turn] Draw 1 card" },
        resolve: (ctx) => ctx.draw(1),
      },
    ],
  }),
  defineCard({
    type: "leader",
    id: "SD02-002",
    name: "Rover (M)",
    character: "Rover (M)",
    set: "SD02",
    imageId: "SD02-002",
    level: 1,
    rarity: 1,
    weapon: "sword",
    element: "spectro",
    effects: [
      {
        condition: ["leader", "judgement"],
        text: {
          th: "[Leader] [Judgement] หากแพ้ให้กับการ์ดสีแดงในการเล่นการ์ดสีเขียว สามารถแสดงการ์ด 1 ใบบนสุดของเด็ค จากนั้นนำขึ้นมือ",
          en: "[Leader] [Judgement] If a green card of yours loses to a red card, you may reveal the top card of your deck, then take it to hand",
        },
        resolve: (ctx) => {
          if (!(ctx.lostTo("red") && ctx.lastPlayedColor() === "green")) return;
          const revealed = ctx.revealTop(1);
          if (revealed.length === 0) return;
          if (ctx.confirm({
            th: "แสดงการ์ด 1 ใบบนสุดของเด็ค นำขึ้นมือไหม",
            en: "Reveal 1 from the top of your deck and take it?",
          })) ctx.deckToHand(1);
        },
      },
    ],
  }),
  defineCard({
    type: "leader",
    id: "SD02-003",
    name: "Sanhua",
    character: "Sanhua",
    set: "SD02",
    imageId: "SD02-003",
    altImageIds: ["SD02-003_4", "SD02-003_4"],
    level: 2,
    rarity: 3,
    weapon: "sword",
    element: "glacio",
    effects: [
      {
        condition: ["leader", "endTurn"],
        text: {
          th: "[Leader] [At end of each turn] นำการ์ดใบบนสุดของเด็ควางที่ Concerto area",
          en: "[Leader] [At end of each turn] Put the top card of your deck into the Concerto area",
        },
        resolve: (ctx) => {
          ctx.topToConcerto(1);
        },
      },
    ],
  }),
  defineCard({
    type: "leader",
    id: "SD02-004",
    name: "Sanhua",
    character: "Sanhua",
    set: "SD02",
    imageId: "SD02-004",
    level: 1,
    rarity: 1,
    weapon: "sword",
    element: "glacio",
    effects: [
      {
        condition: ["leader", "judgement"],
        text: {
          th: "[Leader] [Judgement] หากแพ้ให้กับการ์ดสีเขียวในการเล่นการ์ดสีฟ้า สามารถแสดงการ์ด 1 ใบบนสุดของเด็ค จากนั้นนำขึ้นมือ",
          en: "[Leader] [Judgement] If a blue card of yours loses to a green card, you may reveal the top card of your deck, then take it to hand",
        },
        resolve: (ctx) => {
          if (!(ctx.lostTo("green") && ctx.lastPlayedColor() === "blue")) return;
          const revealed = ctx.revealTop(1);
          if (revealed.length === 0) return;
          if (ctx.confirm({
            th: "แสดงการ์ด 1 ใบบนสุดของเด็ค นำขึ้นมือไหม",
            en: "Reveal 1 from the top of your deck and take it?",
          })) ctx.deckToHand(1);
        },
      },
    ],
  }),
  defineCard({
    type: "leader",
    id: "SD02-005",
    name: "Jinshi",
    character: "Jinshi",
    set: "SD02",
    imageId: "SD02-005",
    altImageIds: ["SD02-005_4"],
    level: 2,
    rarity: 3,
    weapon: "broadblade",
    element: "spectro",
    grants: {
      comboBoost: {
        condition: ["combo"],
        text: { th: "[Combo] การ์ดใบนี้ได้รับ +1 ดาเมจ", en: "[Combo] This card gets +1 damage." },
        resolve: (ctx) => ctx.buff({ cardId: ctx.self.id }, "attack", 1, "battle"),
      },
    },
    effects: [
      {
        // No "combo" here: the [Combo] in the printed text belongs to the
        // ability being handed out (see `grants` above), not to this one.
        // Handing it out is continuous — true for as long as Jinshi leads.
        condition: ["leader"],
        text: {
          th: "[Leader] การ์ดสีแดงของคุณได้รับ “[Combo] การ์ดมบนี้ได้รับ +1 ดาเมจ”",
          en: "[Leader] Your red cards gain “[Combo] This card gains +1 damage”",
        },
        resolve: (ctx) =>
            ctx.grantEffect({ color: "red" }, "comboBoost", "whileActive"),
      },
    ],
  }),
  defineCard({
    type: "leader",
    id: "SD02-006",
    name: "Jinshi",
    character: "Jinshi",
    set: "SD02",
    imageId: "SD02-006",
    level: 1,
    rarity: 1,
    weapon: "broadblade",
    element: "spectro",
    effects: [
      {
        condition: ["leader", "judgement"],
        text: {
          th: "[Leader] [Judgement] หากแพ้ให้กับการ์ดสีฟ้าในการเล้นการ์ดสีแดง สามารถแสดงการ์ด 1 ใบบนสุดของเด็ค จากนั้นนำขึ้นมือ",
          en: "[Leader] [Judgement] If a red card of yours loses to a blue card, you may reveal the top card of your deck, then take it to hand",
        },
        resolve: (ctx) => {
          if (!(ctx.lostTo("blue") && ctx.lastPlayedColor() === "red")) return;
          const revealed = ctx.revealTop(1);
          if (revealed.length === 0) return;
          if (ctx.confirm({
            th: "แสดงการ์ด 1 ใบบนสุดของเด็ค นำขึ้นมือไหม",
            en: "Reveal 1 from the top of your deck and take it?",
          })) ctx.deckToHand(1);
        },
      },
    ],
  }),
  defineCard({
    type: "action",
    id: "SD02-007",
    name: "Slash of Breaking Dawn • Basic Attack",
    character: "Jinshi",
    set: "SD02",
    imageId: "SD02-007",
    cost: 0,
    color: "red",
    speed: 7,
    attack: 1,
    rarity: 1,
    subtypes: ["Normal Attack", "Basic Attack"],
    effects: [],
  }),
  defineCard({
    type: "action",
    id: "SD02-008",
    name: "Slash of Breaking Dawn • Dodge Counter",
    character: "Jinshi",
    set: "SD02",
    imageId: "SD02-008",
    cost: 0,
    color: "blue",
    speed: null,
    attack: 3,
    rarity: 1,
    subtypes: ["Dodge Counter"],
    effects: [],
  }),
  defineCard({
    type: "action",
    id: "SD02-009",
    name: "Loong's Halo",
    character: "Jinshi",
    set: "SD02",
    imageId: "SD02-009",
    cost: 0,
    color: "red",
    speed: 0,
    attack: 0,
    rarity: 1,
    subtypes: ["Intro Skill"],
    effects: [
      {
        condition: ["combo"],
        text: {
          th: "[Combo] เปลี่ยน Leader หาก Jinshi เป็นตัวที่ถูกสลับ การใบนี้ได้รับ +2 ดาเมจ",
          en: "[Combo] Switch Leaders; if 「Jinshi」 is one of the switched characters, this card gains +2 damage",
        },
        resolve: (ctx) => {
            const back = ctx.board().back;
            if (back.length === 0) return;
            const chosen = ctx.chooseOption(
              { th: "สลับ Leader ไปตัวไหน", en: "Switch your Leader to?" },
              [
                ...back.map((slot) => ({ value: slot.card.name, label: { th: slot.card.name, en: slot.card.name } })),
                { value: "", label: { th: "ไม่สลับ", en: "Do not switch" } },
              ]
            );
            if (!chosen) return;
            // "if 「Jinshi」 is one of the switched characters" — the character
            // leaving the Leader slot is switched too, not only the one arriving
            // (906.2, and FAQ #52 on SD01-009 answers exactly this).
            if (ctx.switchLeaderTo(chosen).includes("Jinshi")) { ctx.buff({ cardId: ctx.self.id }, "attack", 2, "battle"); }
          },
      },
    ],
  }),
  defineCard({
    type: "action",
    id: "SD02-010",
    name: "Incarnation",
    character: "Jinshi",
    set: "SD02",
    imageId: "SD02-010",
    cost: 1,
    color: "green",
    speed: 13,
    attack: 0,
    rarity: 1,
    subtypes: ["Forte Circuit"],
    effects: [
      {
        condition: ["counter"],
        text: { th: "[Counter] ในเทิร์นนี้ ไม่สามารถสลับ Leader ได้", en: "[Counter] This turn, you cannot switch Leaders" },
        resolve: (ctx) => ctx.restrict("noLeaderSwitch"),
      },
      {
        condition: ["judgement", "follow"],
        followCount: 8,
        text: {
          th: "[Judgement] หากชนะ จั่วการ์ด 3 ใบ ได้รับ +8[follow-up attack]",
          en: "[Judgement] If you win, draw 3 cards and gain +8 [follow-up attack]",
        },
        resolve: (ctx) => {
            if (!ctx.wonLastBattle()) return;
            ctx.draw(3);
            ctx.grantFollowUp(8);
          },
      },
    ],
  }),
  defineCard({
    type: "action",
    id: "SD02-011",
    name: "Purge of Light",
    character: "Jinshi",
    set: "SD02",
    imageId: "SD02-011",
    altImageIds: ["SD02-011_3"],
    cost: 3,
    color: "red",
    speed: 13,
    attack: 5,
    rarity: 1,
    subtypes: ["Resonance Liberation"],
    effects: [
      {
        condition: ["leader", "combo"],
        text: {
          th: "[Leader Skill] [Combo] หากใน Action area มีการ์ด 3 ใบหรือมากกว่า การ์ดใบนี้ได้รับ +3 ดาเมจ",
          en: "[Leader Skill] [Combo] If your Action area has 3 or more cards, this card gains +3 damage",
        },
        resolve: (ctx) => {
            if (ctx.actionZone().length >= 3) ctx.buff({ cardId: ctx.self.id }, "attack", 3, "battle");
          },
      },
    ],
  }),
  defineCard({
    type: "action",
    id: "SD02-012",
    name: "Frigid Light • Basic Attack",
    character: "Sanhua",
    set: "SD02",
    imageId: "SD02-012",
    cost: 0,
    color: "red",
    speed: 8,
    attack: 1,
    rarity: 1,
    subtypes: ["Normal Attack", "Basic Attack"],
    effects: [],
  }),
  defineCard({
    type: "action",
    id: "SD02-013",
    name: "Frigid Light • Dodge",
    character: "Sanhua",
    set: "SD02",
    imageId: "SD02-013",
    cost: 0,
    color: "blue",
    speed: null,
    attack: 0,
    rarity: 1,
    subtypes: ["Dodge"],
    effects: [
      {
        condition: ["judgement", "follow"],
        followCount: 2,
        text: { th: "[Judgement] หากชนะ ได้รับ 2[follow-up attack]", en: "[Judgement] If you win, gain +2 [follow-up attack]" },
        resolve: (ctx) => { if (ctx.wonLastBattle()) ctx.grantFollowUp(2); },
      },
    ],
  }),
  defineCard({
    type: "action",
    id: "SD02-014",
    name: "Silversnow",
    character: "Sanhua",
    set: "SD02",
    imageId: "SD02-014",
    cost: 0,
    color: "red",
    speed: 0,
    attack: 0,
    rarity: 1,
    subtypes: ["Intro Skill"],
    effects: [
      {
        condition: ["combo"],
        text: {
          th: "[Combo] เปลี่ยน Leader หาก Sanhua เป็นตัวที่ถูกสลับ นำการ์ด 1 ใบบนสุดของเด็ควางที่ Concerto area",
          en: "[Combo] Switch Leaders; if 「Sanhua」 is one of the switched characters, put the top card of your deck into the Concerto area",
        },
        resolve: (ctx) => {
            const back = ctx.board().back;
            if (back.length === 0) return;
            const chosen = ctx.chooseOption(
              { th: "สลับ Leader ไปตัวไหน", en: "Switch your Leader to?" },
              [
                ...back.map((slot) => ({ value: slot.card.name, label: { th: slot.card.name, en: slot.card.name } })),
                { value: "", label: { th: "ไม่สลับ", en: "Do not switch" } },
              ]
            );
            if (!chosen) return;
            // "if 「Sanhua」 is one of the switched characters" — the character
            // leaving the Leader slot is switched too, not only the one arriving
            // (906.2, and FAQ #52 on SD01-009 answers exactly this).
            if (ctx.switchLeaderTo(chosen).includes("Sanhua")) { ctx.topToConcerto(1); }
          },
      },
    ],
  }),
  defineCard({
    type: "action",
    id: "SD02-015",
    name: "Eternal Frost",
    character: "Sanhua",
    set: "SD02",
    imageId: "SD02-015",
    cost: 1,
    color: "red",
    speed: 9,
    attack: 3,
    rarity: 1,
    subtypes: ["Resonance Skill"],
    effects: [
      {
        condition: ["leader", "judgement"],
        text: {
          th: "[Leader Skill] [Judgement] หากชนะ นำการ์ด 2 ใบบนสุดของเด็ควางที่ Concerto area",
          en: "[Leader Skill] [Judgement] If you win, put the top 2 cards of your deck into the Concerto area",
        },
        resolve: (ctx) => {
          if (!(ctx.wonLastBattle())) return;
          ctx.topToConcerto(2);
        },
      },
    ],
  }),
  defineCard({
    type: "action",
    id: "SD02-016",
    name: "Glacial Gaze",
    character: "Sanhua",
    set: "SD02",
    imageId: "SD02-016",
    altImageIds: ["SD02-016_3"],
    cost: 2,
    color: "red",
    speed: 13,
    attack: 4,
    rarity: 1,
    subtypes: ["Resonance Liberation"],
    effects: [
      {
        condition: ["leader", "judgement"],
        text: {
          th: "[Leader Skill] [Judgement] หากชนะ ในรอบถัดไปฝ่ายตรงข้ามไม่สามารถใช้โจมตีต่อเนื่องได้",
          en: "[Leader Skill] [Judgement] If you win, your opponent cannot Combo next round",
        },
        resolve: (ctx) => {
            if (ctx.wonLastBattle()) ctx.restrictNextTurn("noFollowUp", ctx.opponentId);
          },
      },
    ],
  }),
  defineCard({
    type: "action",
    id: "SD02-017",
    name: "Vibration Manifestation • Basic Attack",
    character: "Rover (M)",
    set: "SD02",
    imageId: "SD02-017",
    cost: 0,
    color: "red",
    speed: 8,
    attack: 1,
    rarity: 1,
    subtypes: ["Normal Attack", "Basic Attack"],
    effects: [],
  }),
  defineCard({
    type: "action",
    id: "SD02-018",
    name: "Vibration Manifestation•Dodge",
    character: "Rover (M)",
    set: "SD02",
    imageId: "SD02-018",
    cost: 0,
    color: "blue",
    speed: null,
    attack: 0,
    rarity: 1,
    subtypes: ["Dodge"],
    effects: [
      {
        condition: ["judgement"],
        text: {
          th: "[Judgement] หากชนะ จั่วการ์ด 1 ใบ จากนั้นทิ้งการ์ดในมือ 1 ใบ",
          en: "[Judgement] If you win, draw 1 card, then discard 1 card from hand",
        },
        resolve: (ctx) => {
            if (!ctx.wonLastBattle()) return;
            ctx.draw(1);
            const pick = ctx.chooseCard({ th: "เลือกการ์ดที่จะทิ้ง", en: "Discard which card?" }, ctx.hand());
            if (pick) ctx.discardCards([pick]);
          },
      },
    ],
  }),
  defineCard({
    type: "action",
    id: "SD02-019",
    name: "Waveshock",
    character: "Rover (M)",
    set: "SD02",
    imageId: "SD02-019",
    cost: 0,
    color: "red",
    speed: 0,
    attack: 0,
    rarity: 1,
    subtypes: ["Intro Skill"],
    effects: [
      {
        condition: ["combo"],
        text: {
          th: "[Combo] เปลี่ยน Leader หาก Rover (M) เป็นตัวที่ถูกสลับ จั่วการ์ด 1 ใบ",
          en: "[Combo] Switch Leaders; if 「Rover (M)」 is one of the switched characters, draw 1 card",
        },
        resolve: (ctx) => {
            const back = ctx.board().back;
            if (back.length === 0) return;
            const chosen = ctx.chooseOption(
              { th: "สลับ Leader ไปตัวไหน", en: "Switch your Leader to?" },
              [
                ...back.map((slot) => ({ value: slot.card.name, label: { th: slot.card.name, en: slot.card.name } })),
                { value: "", label: { th: "ไม่สลับ", en: "Do not switch" } },
              ]
            );
            if (!chosen) return;
            // "if 「Rover (M)」 is one of the switched characters" — the character
            // leaving the Leader slot is switched too, not only the one arriving
            // (906.2, and FAQ #52 on SD01-009 answers exactly this).
            if (ctx.switchLeaderTo(chosen).includes("Rover (M)")) { ctx.draw(1); }
          },
      },
    ],
  }),
  defineCard({
    type: "action",
    id: "SD02-020",
    name: "Sensor",
    character: "Rover (M)",
    set: "SD02",
    imageId: "SD02-020",
    cost: 0,
    color: "green",
    speed: 5,
    attack: 0,
    rarity: 1,
    subtypes: ["Utilities"],
    effects: [
      {
        condition: ["judgement"],
        text: {
          th: "[Judgement] หากชนะ จั่วการ์ด 1 ใบ ฝ่ายตรงข้ามแสดงการ์ดในมือ",
          en: "[Judgement] If you win, draw 1 card and your opponent reveals their hand",
        },
        resolve: (ctx) => {
            if (!ctx.wonLastBattle()) return;
            ctx.draw(1);
            ctx.revealHand(ctx.opponentId);
          },
      },
    ],
  }),
  defineCard({
    type: "action",
    id: "SD02-021",
    name: "Grapple",
    character: "Rover (M)",
    set: "SD02",
    imageId: "SD02-021",
    cost: 1,
    color: "green",
    speed: 8,
    attack: 0,
    rarity: 1,
    subtypes: ["Utilities", "Airborn"],
    effects: [
      {
        condition: ["judgement", "follow"],
        followCount: 2,
        text: {
          th: "[Judgement] หากชนะ จั่วการ์ด 1 ใบ ได้รับ +2[follow-up attack]",
          en: "[Judgement] If you win, draw 1 card and gain +2 [follow-up attack]",
        },
        resolve: (ctx) => {
            if (!ctx.wonLastBattle()) return;
            ctx.draw(1);
            ctx.grantFollowUp(2);
          },
      },
    ],
  }),
  defineCard({
    type: "action",
    id: "SD02-022",
    name: "Resonating Slashes",
    character: "Rover (M)",
    set: "SD02",
    imageId: "SD02-022",
    cost: 1,
    color: "red",
    speed: 13,
    attack: 3,
    rarity: 1,
    subtypes: ["Resonance Skill"],
    effects: [],
  }),
  defineCard({
    type: "action",
    id: "SD02-023",
    name: "Echoing Orchestra",
    character: "Rover (M)",
    set: "SD02",
    imageId: "SD02-023",
    altImageIds: ["SD02-023_3"],
    cost: 2,
    color: "red",
    speed: 13,
    attack: 5,
    rarity: 1,
    subtypes: ["Resonance Liberation"],
    effects: [],
  }),
];
