// Builds/refreshes the card set files from the downloaded card images.
//
// One entry per printed card number. Parallel printings (BP01-005_2,
// BP01-005_2PR, BP01-001_4 ...) are NOT separate entries — they fold into the
// base card's altImageIds.
//
// Cards you have already filled in are never touched: the script only appends
// entries for card numbers that have no entry yet, so it is safe to re-run
// after downloading more images.
//
// Run with: npm run sync:cards
import { readdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { baseCardId } from "../src/cards";

const HERE = dirname(fileURLToPath(import.meta.url));
const IMAGE_DIR = join(HERE, "..", "..", "client", "public", "cards");
const SETS_DIR = join(HERE, "..", "src", "sets");

/** Card images are "<SET>-<NNN>" with an optional parallel-art suffix. */
const CARD_FILE = /^([A-Za-z]{2}[0-9]{2})-([0-9]{3})(_[0-9A-Za-z]+)?\.(jpg|png)$/i;

interface Group {
  set: string;
  id: string;
  main: string | null;
  parallels: string[];
}

const groups = new Map<string, Group>();
const skipped: string[] = [];

for (const file of readdirSync(IMAGE_DIR)) {
  const match = CARD_FILE.exec(file);
  if (!match) {
    skipped.push(file);
    continue;
  }
  const set = match[1].toUpperCase();
  const id = `${set}-${match[2]}`;
  const imageId = file.replace(/\.(jpg|png)$/i, "");

  let group = groups.get(id);
  if (!group) {
    group = { set, id, main: null, parallels: [] };
    groups.set(id, group);
  }
  if (baseCardId(imageId) === imageId) group.main = imageId;
  else group.parallels.push(imageId);
}

const bySet = new Map<string, Group[]>();
for (const group of [...groups.values()].sort((a, b) => a.id.localeCompare(b.id))) {
  const list = bySet.get(group.set) ?? [];
  list.push(group);
  bySet.set(group.set, list);
}

const TODO_NOTE =
  "TODO — ยังไม่ได้กรอก (ถ้าเป็นการ์ดตัวละคร เปลี่ยน type เป็น leader แล้วใส่ level แทน cost/color/speed/attack/chase)";

function stubFor(group: Group, set: string): string {
  const imageId = group.main ?? group.parallels[0];
  const alt = group.parallels.sort();
  const altLine =
    alt.length > 0 ? `\n    altImageIds: [${alt.map((id) => `"${id}"`).join(", ")}],` : "";

  return `  defineCard({
    type: "action",
    id: "${group.id}",
    name: "",
    character: "",
    set: "${set}",
    imageId: "${imageId}",${altLine}
    cost: 0,
    color: "red",
    speed: 0,
    attack: 0,
    chase: null,
    effects: [],
    notes: { th: "${TODO_NOTE}" },
  }),`;
}

let added = 0;
let kept = 0;

for (const [set, cardGroups] of [...bySet.entries()].sort()) {
  const path = join(SETS_DIR, `${set}.ts`);
  const existing = existsSync(path) ? readFileSync(path, "utf8") : "";

  const newStubs: string[] = [];
  for (const group of cardGroups) {
    // Already present in the file? Leave it completely alone.
    if (existing.includes(`id: "${group.id}"`)) {
      kept += 1;
      continue;
    }
    newStubs.push(stubFor(group, set));
    added += 1;
  }

  if (existing && newStubs.length === 0) {
    console.log(`${set}: ${cardGroups.length} cards, nothing new`);
    continue;
  }

  let out: string;
  if (existing) {
    // Append before the closing bracket of the exported array.
    const close = existing.lastIndexOf("];");
    out = `${existing.slice(0, close)}${newStubs.join("\n")}\n${existing.slice(close)}`;
  } else {
    out = `// ${set} — one entry per printed card number.
//
// Each card carries what is printed on it AND what it does. See
// src/cardDef.ts for the shape, and _EXAMPLE.ts for a filled-in card.
//
// Generated by \`npm run sync:cards\`; new card numbers are appended and
// anything already here is left untouched. Fill these in by hand.
import { defineCard } from "../cardDef";
import type { CardDef } from "../cardDef";

export const ${set}: CardDef[] = [
${newStubs.join("\n")}
];
`;
  }

  writeFileSync(path, out, "utf8");
  console.log(`${set}: ${cardGroups.length} cards -> src/sets/${set}.ts`);
}

console.log(`\n${added} stub(s) added, ${kept} existing card(s) kept.`);
if (skipped.length > 0) {
  console.log(`\nSkipped ${skipped.length} file(s) that don't match <SET>-<NNN>:`);
  for (const file of skipped) console.log(`   ${file}`);
}
