// Shared types used by both the client and server.
// Keeping these in one place means a socket event added on the server
// shows up as a type error on the client (and vice versa) if it's unused.

import type { MatchState } from "./game";
import type { ChoiceAnswer, PendingChoice } from "./cardDef";
import type { DeckList } from "./deckList";
import type { ResolvedEffect } from "./effects";
import type { MatchIntent } from "./match";
import type { LogLine } from "./log";

/**
 * Which side of the table a player sits on. These double as the engine's
 * player ids, so a MatchState coming off the wire needs no translation.
 */
export type Seat = "p1" | "p2";
export const SEATS: Seat[] = ["p1", "p2"];

export interface Player {
  /**
   * Stable identity, generated by the client and kept in localStorage —
   * NOT the socket id, which changes on every refresh. This is what lets
   * someone reload mid-match and sit back down in the same seat.
   */
  id: string;
  name: string;
  seat: Seat;
  isHost: boolean;
  connected: boolean;
}

export type RoomStatus = "waiting" | "playing" | "finished";

/**
 * Who may find this room.
 *
 * "public" lists it in the room browser for anyone to join; "private" is
 * reachable only by typing its code. Both are joined the same way — this
 * only decides whether the code has to be shared by hand.
 */
export type RoomVisibility = "public" | "private";

export interface Room {
  code: string; // short shareable join code, e.g. "AB12"
  players: Player[];
  status: RoomStatus;
  maxPlayers: number;
  visibility: RoomVisibility;
  /**
   * The three characters each seat is bringing, once they have chosen a
   * deck. The deck list itself stays on the server — an opponent should not
   * be handed your 40 cards before the first turn — but who is on the field
   * is public the moment the match starts anyway.
   */
  picks: Partial<Record<Seat, string[]>>;
  /** True once a match is running, so a rejoining client goes to the board. */
  inMatch: boolean;
}

/** One row in the room browser. */
export interface RoomSummary {
  code: string;
  hostName: string;
  players: number;
  maxPlayers: number;
  /** Characters already chosen, so a browser shows what is being brought. */
  picks: string[][];
}

export interface ApiError {
  message: string;
}

export interface ChatMessage {
  id: string;
  /** Empty for the room's own announcements ("X joined"). */
  from: string;
  text: string;
  at: number;
}

/**
 * One player's view of the match, as the server sends it.
 *
 * `view` is already filtered through viewFor() for the recipient, so a client
 * physically does not have the other hand — hiding it in the UI would be a
 * promise the client could not keep.
 */
export interface MatchUpdate {
  matchId: string;
  seat: Seat;
  view: MatchState;
  /** Names by seat, for labelling the two sides of the board. */
  names: Record<string, string>;
  connected: Record<string, boolean>;
  /** The open question, sent only to the player who has to answer it. */
  pending: PendingChoice | null;
  /** Who is being asked, so the other player sees "waiting" instead of nothing. */
  askingSeat: Seat | null;
  /** Whose move is waiting on that answer — the only seat allowed to drop it. */
  actorSeat: Seat | null;
  /** Effects with no code written — the players apply these themselves. */
  manual: ResolvedEffect[];
  log: LogLine[];
  /** Why this player's own last move was refused, if it was. */
  error: string | null;
}

// --- Socket.IO event contracts -------------------------------------------

export interface JoinResult {
  room: Room;
  seat: Seat;
  playerId: string;
}

export interface ClientToServerEvents {
  createRoom: (
    payload: { playerName: string; playerId: string; visibility: RoomVisibility },
    callback: (result: JoinResult | { error: string }) => void
  ) => void;

  joinRoom: (
    payload: { roomCode: string; playerName: string; playerId: string },
    callback: (result: JoinResult | { error: string }) => void
  ) => void;

  leaveRoom: (payload: { roomCode: string }) => void;

  /**
   * Lobby: hand in the deck this seat will play. The server keeps it and
   * only publishes the three character names.
   */
  submitDeck: (payload: { deck: DeckList }, callback: (result: { ok: true } | { error: string }) => void) => void;

  /**
   * Start or stop receiving the public room list. Browsing is opt-in so an
   * update isn't pushed at every socket in a match.
   */
  watchRooms: (payload: { watching: boolean }) => void;

  /** Host only. Deals both decks and puts the match on the table. */
  startMatch: (callback: (result: { ok: true } | { error: string }) => void) => void;

  /** Play a move. Rejected moves come back as `error` on the next update. */
  matchIntent: (payload: { intent: MatchIntent }) => void;

  /** Answer the open question the server asked this player. */
  matchAnswer: (payload: { answer: ChoiceAnswer }) => void;

  /** Back out of an open question, leaving the board as it was. */
  cancelChoice: () => void;

  /** Deal a fresh game to the same two seats. */
  restartMatch: () => void;

  sendChat: (payload: { text: string }) => void;
}

export interface ServerToClientEvents {
  roomUpdate: (room: Room) => void;
  /** The public rooms waiting for an opponent, for anyone watching. */
  roomsUpdate: (rooms: RoomSummary[]) => void;
  matchUpdate: (update: MatchUpdate) => void;
  matchEnded: () => void;
  chatMessage: (message: ChatMessage) => void;
  /** The backlog, sent once on joining so a latecomer sees what was said. */
  chatHistory: (messages: ChatMessage[]) => void;
  errorMessage: (error: ApiError) => void;
}

export interface InterServerEvents {
  // reserved for future multi-node setups (not needed yet)
}

export interface SocketData {
  /** The stable player id, not the socket id. */
  playerId: string;
  roomCode: string | null;
}
